using Haven.Application;
using Haven.Core;
using Haven.UI;
using Haven.UI.Components;
using HavenButton = Haven.UI.Components.Button;
using HavenText = Haven.UI.Components.Text;

namespace Haven.Desktop.Views.Pages.Write;

internal enum WordWriteRibbonTab { Home, Insert, Layout, Review }

/// <summary>Word-class Haven.UI surface for Write. Platform code only hosts this scene.</summary>
internal sealed class WordWriteHavenScene : IDisposable
{
    private bool _suppress;
    private bool _disposed;
    private WordWriteRibbonTab _tab = WordWriteRibbonTab.Home;
    private WriteDocumentEditor? _editor;
    private readonly Dictionary<Guid, Input> _blockInputs = [];
    private string _find = string.Empty, _replace = string.Empty, _comment = string.Empty, _citationTitle = string.Empty, _citationAuthors = string.Empty, _citationUrl = string.Empty;

    public WordWriteHavenScene()
    {
        Root = new Page { Name = "Write.Word.Root", Layout = HavenLayout.Grid, Columns = "1fr", Rows = "Auto Auto Auto 1fr Auto" }; Root.SetValue(HavenProperties.Background, "Surface"); Root.SetValue(HavenProperties.Overflow, HavenOverflow.Clip);
        Header = new Container { Name = "Write.Word.Header", Layout = HavenLayout.Grid, Columns = "1fr Auto", Rows = "Auto" }; Header.SetValue(HavenProperties.Padding, HavenThickness.Parse("10px 18px 6px 18px")); Header.SetValue(HavenProperties.Gap, HavenLength.Px(10)); TitleInput = Field("Write.Word.Title", "Document title", "Untitled document"); TitleInput.SetValue(HavenProperties.FontSize, 20d); TitleInput.SetValue(HavenProperties.FontWeight, 700); Header.Add(TitleInput); DocumentPositionText = Caption("Local document"); DocumentPositionText.SetValue(HavenProperties.Column, 1); DocumentPositionText.SetValue(HavenProperties.VerticalAlignment, HavenVerticalAlignment.Center); Header.Add(DocumentPositionText); Root.Add(Header);
        QuickBar = Bar("Write.Word.Quick", 1); PreviousButton = Btn("Write.Previous", "Previous"); NextButton = Btn("Write.Next", "Next"); NewButton = Btn("Write.New", "New"); ImportButton = Btn("Write.Import", "Import"); ExportButton = Btn("Write.Export", "Export"); SaveButton = Btn("Write.Save", "Save", ButtonVariant.Primary); UndoButton = Btn("Write.Undo", "Undo"); RedoButton = Btn("Write.Redo", "Redo"); foreach (var value in new[] { PreviousButton, NextButton, NewButton, ImportButton, ExportButton, SaveButton, UndoButton, RedoButton }) QuickBar.Add(value); Root.Add(QuickBar);
        Ribbon = new Container { Name = "Write.Word.Ribbon", Layout = HavenLayout.Vertical }; Ribbon.SetValue(HavenProperties.Row, 2); Ribbon.SetValue(HavenProperties.Background, "SurfaceRaised"); Ribbon.SetValue(HavenProperties.Padding, HavenThickness.Parse("5px 18px 9px 18px")); Ribbon.SetValue(HavenProperties.Gap, HavenLength.Px(5)); RibbonTabs = Bar("Write.Word.RibbonTabs", 0); HomeTab = Btn("Write.Tab.Home", "Home"); InsertTab = Btn("Write.Tab.Insert", "Insert"); LayoutTab = Btn("Write.Tab.Layout", "Layout"); ReviewTab = Btn("Write.Tab.Review", "Review"); foreach (var value in new[] { HomeTab, InsertTab, LayoutTab, ReviewTab }) RibbonTabs.Add(value); Ribbon.Add(RibbonTabs); RibbonContent = new Container { Name = "Write.Word.RibbonContent", Layout = HavenLayout.Horizontal }; RibbonContent.SetValue(HavenProperties.Gap, HavenLength.Px(7)); RibbonContent.SetValue(HavenProperties.Overflow, HavenOverflow.Scroll); Ribbon.Add(RibbonContent); Root.Add(Ribbon);
        Scroller = new Container { Name = "Write.Word.Scroller", Layout = HavenLayout.Vertical }; Scroller.SetValue(HavenProperties.Row, 3); Scroller.SetValue(HavenProperties.Overflow, HavenOverflow.Scroll); Scroller.SetValue(HavenProperties.Padding, HavenThickness.Parse("22px 32px 40px 32px")); DocumentHost = new Container { Name = "Write.Word.Document", Layout = HavenLayout.Vertical }; DocumentHost.SetValue(HavenProperties.HorizontalAlignment, HavenHorizontalAlignment.Center); DocumentHost.SetValue(HavenProperties.Background, "SurfaceRaised"); DocumentHost.SetValue(HavenProperties.BorderColor, "Border"); DocumentHost.SetValue(HavenProperties.BorderWidth, HavenLength.Px(1)); DocumentHost.SetValue(HavenProperties.Radius, HavenCornerRadius.Uniform(HavenLength.Px(8))); DocumentHost.SetValue(HavenProperties.Gap, HavenLength.Px(11)); Scroller.Add(DocumentHost); Root.Add(Scroller);
        StatusText = Caption("Opening local documents…"); StatusText.Name = "Write.Status"; StatusText.SetValue(HavenProperties.Row, 4); StatusText.SetValue(HavenProperties.Padding, HavenThickness.Parse("8px 18px")); Root.Add(StatusText);
        TitleInput.Invalidated += OnTitleInvalidated; PreviousButton.Invoked += (_, _) => PreviousRequested?.Invoke(this, EventArgs.Empty); NextButton.Invoked += (_, _) => NextRequested?.Invoke(this, EventArgs.Empty); NewButton.Invoked += (_, _) => NewRequested?.Invoke(this, EventArgs.Empty); ImportButton.Invoked += (_, _) => ImportRequested?.Invoke(this, EventArgs.Empty); ExportButton.Invoked += (_, _) => ExportRequested?.Invoke(this, EventArgs.Empty); SaveButton.Invoked += (_, _) => SaveRequested?.Invoke(this, EventArgs.Empty); UndoButton.Invoked += (_, _) => Apply(editor => editor.Undo()); RedoButton.Invoked += (_, _) => Apply(editor => editor.Redo()); HomeTab.Invoked += (_, _) => SetTab(WordWriteRibbonTab.Home); InsertTab.Invoked += (_, _) => SetTab(WordWriteRibbonTab.Insert); LayoutTab.Invoked += (_, _) => SetTab(WordWriteRibbonTab.Layout); ReviewTab.Invoked += (_, _) => SetTab(WordWriteRibbonTab.Review);
    }

    public event EventHandler? PreviousRequested; public event EventHandler? NextRequested; public event EventHandler? NewRequested; public event EventHandler? ImportRequested; public event EventHandler? ExportRequested; public event EventHandler? SaveRequested; public event EventHandler? ImageRequested; public event EventHandler? DocumentChanged;
    public event Action<string>? TitleChanged { add { } remove { } }
    public event Action<WriteBlockTextChangedEventArgs>? BlockTextChanged { add { } remove { } }
    public Page Root { get; } public Container Header { get; } public Container QuickBar { get; } public Container Ribbon { get; } public Container RibbonTabs { get; } public Container RibbonContent { get; } public Container Scroller { get; } public Container DocumentHost { get; }
    public Input TitleInput { get; } public HavenText DocumentPositionText { get; } public HavenText StatusText { get; }
    public HavenButton PreviousButton { get; } public HavenButton NextButton { get; } public HavenButton NewButton { get; } public HavenButton ImportButton { get; } public HavenButton ExportButton { get; } public HavenButton SaveButton { get; } public HavenButton UndoButton { get; } public HavenButton RedoButton { get; } public HavenButton HomeTab { get; } public HavenButton InsertTab { get; } public HavenButton LayoutTab { get; } public HavenButton ReviewTab { get; }
    public IReadOnlyDictionary<Guid, Input> BlockInputs => _blockInputs; public NotesDocument? Document => _editor?.Document;

    public void SetDocument(NotesDocument document, int index, int count) { if (_editor is not null) _editor.Changed -= OnEditorChanged; _editor = new WriteDocumentEditor(document); _editor.Changed += OnEditorChanged; _suppress = true; try { TitleInput.Text = document.Title; } finally { _suppress = false; } DocumentPositionText.Content = $"{index + 1} of {Math.Max(1, count)} · v{document.Version}"; RebuildAll(); }
    public void SetTitleFromModel(string title) { _suppress = true; try { TitleInput.Text = title ?? string.Empty; } finally { _suppress = false; } }
    public void SetStatus(string text) => StatusText.Content = text ?? string.Empty;
    public void InsertMedia(NotesMediaData media) { if (_editor is null) return; _editor.InsertMedia(media); RebuildAll(); }
    public void SetBusy(bool busy) { foreach (var button in Root.DescendantsAndSelf().OfType<HavenButton>()) button.SetValue(HavenProperties.Enabled, !busy); TitleInput.SetValue(HavenProperties.Enabled, !busy); if (!busy) RefreshCommands(); }

    private void OnTitleInvalidated(object? sender, EventArgs e) { if (_suppress || _editor is null || TitleInput.Text == _editor.Document.Title) return; _editor.SetTitle(TitleInput.Text); }
    private void OnEditorChanged(object? sender, EventArgs e) { if (_editor is null) return; _suppress = true; try { if (TitleInput.Text != _editor.Document.Title) TitleInput.Text = _editor.Document.Title; } finally { _suppress = false; } UpdateStats(); RefreshCommands(); DocumentChanged?.Invoke(this, EventArgs.Empty); }
    private void SetTab(WordWriteRibbonTab tab) { _tab = tab; RebuildRibbon(); }
    private void RebuildAll() { RebuildRibbon(); RebuildDocument(); UpdateStats(); RefreshCommands(); }
    private void RefreshCommands() { if (_editor is null) return; UndoButton.SetValue(HavenProperties.Enabled, _editor.CanUndo); RedoButton.SetValue(HavenProperties.Enabled, _editor.CanRedo); HomeTab.Variant = _tab == WordWriteRibbonTab.Home ? ButtonVariant.Primary : ButtonVariant.Tertiary; InsertTab.Variant = _tab == WordWriteRibbonTab.Insert ? ButtonVariant.Primary : ButtonVariant.Tertiary; LayoutTab.Variant = _tab == WordWriteRibbonTab.Layout ? ButtonVariant.Primary : ButtonVariant.Tertiary; ReviewTab.Variant = _tab == WordWriteRibbonTab.Review ? ButtonVariant.Primary : ButtonVariant.Tertiary; }
    private void RebuildRibbon() { RibbonContent.Children.ToList().ForEach(child => child.Parent?.Remove(child)); if (_editor is null) return; switch (_tab) { case WordWriteRibbonTab.Home: Home(); break; case WordWriteRibbonTab.Insert: Insert(); break; case WordWriteRibbonTab.Layout: Layout(); break; case WordWriteRibbonTab.Review: Review(); break; } RefreshCommands(); }

    private void Home()
    {
        var editor = _editor!; var block = editor.SelectedBlock; var run = editor.ActiveRun; var styles = editor.Document.Styles; var styleIndex = block is null ? -1 : styles.FindIndex(value => value.Id.Equals(block.StyleId, StringComparison.OrdinalIgnoreCase)); var style = Choice("Write.Home.Style", "Paragraph style", styles.Select(value => value.Id).ToArray(), styleIndex); style.SelectionChanged += (_, _) => { if (style.SelectedItem is { } id) Apply(value => { value.ApplyStyle(id); return true; }); }; RibbonContent.Add(style);
        var font = Field("Write.Home.Font", "Font family", "Font"); font.Text = run?.FontFamily ?? "Montserrat"; font.SetValue(HavenProperties.Width, HavenLength.Px(145)); font.Invalidated += (_, _) => { if (!_suppress && run is not null && !font.Text.Equals(run.FontFamily, StringComparison.Ordinal)) editor.SetFontFamily(font.Text); }; RibbonContent.Add(font);
        RibbonContent.Add(NumberField("Write.Home.Size", "Font size", run?.FontSize ?? 14, editor.SetFontSize, 68)); RibbonContent.Add(Format("Write.Home.Bold", "B", run?.Bold == true, WriteCharacterFormat.Bold)); RibbonContent.Add(Format("Write.Home.Italic", "I", run?.Italic == true, WriteCharacterFormat.Italic)); RibbonContent.Add(Format("Write.Home.Underline", "U", run?.Underline == true, WriteCharacterFormat.Underline)); RibbonContent.Add(Format("Write.Home.Strike", "S", run?.StrikeThrough == true, WriteCharacterFormat.StrikeThrough));
        var fore = Field("Write.Home.Foreground", "Text colour", "#FF000000"); fore.Text = run?.Foreground ?? "#FFEEEEEE"; fore.SetValue(HavenProperties.Width, HavenLength.Px(112)); fore.Invalidated += (_, _) => { if (!_suppress) editor.SetForeground(fore.Text); }; RibbonContent.Add(fore); var high = Field("Write.Home.Highlight", "Highlight colour", "#FFFFFF00"); high.Text = run?.Background ?? "#00000000"; high.SetValue(HavenProperties.Width, HavenLength.Px(112)); high.Invalidated += (_, _) => { if (!_suppress) editor.SetBackground(high.Text); }; RibbonContent.Add(high); var link = Field("Write.Home.Link", "Hyperlink", "https://"); link.Text = run?.Link ?? string.Empty; link.SetValue(HavenProperties.Width, HavenLength.Px(150)); link.Invalidated += (_, _) => { if (!_suppress) editor.SetLink(link.Text); }; RibbonContent.Add(link);
        foreach (var alignment in Enum.GetValues<NotesTextAlignment>()) { var button = Btn("Write.Align." + alignment, alignment.ToString(), block?.Paragraph.Alignment == alignment ? ButtonVariant.Primary : ButtonVariant.Tertiary); button.Invoked += (_, _) => Apply(value => { value.SetAlignment(alignment); return true; }); RibbonContent.Add(button); }
        RibbonContent.Add(NumberField("Write.Home.LineSpacing", "Line spacing", block?.Paragraph.LineSpacing ?? 1.25, editor.SetLineSpacing, 78)); RibbonContent.Add(NumberField("Write.Home.Indent", "Left indent", block?.Paragraph.IndentLeft ?? 0, editor.SetLeftIndent, 78)); RibbonContent.Add(NumberField("Write.Home.FirstIndent", "First-line indent", block?.Paragraph.FirstLineIndent ?? 0, editor.SetFirstLineIndent, 86));
        var split = Btn("Write.Home.SplitRun", "Split run"); split.Invoked += (_, _) => Apply(value => value.SplitRunAtCaret()); RibbonContent.Add(split); var merge = Btn("Write.Home.MergeRun", "Merge run"); merge.Invoked += (_, _) => Apply(value => value.MergeRunWithPrevious()); RibbonContent.Add(merge); var up = Btn("Write.Home.Up", "↑ Block"); up.Invoked += (_, _) => Apply(value => value.MoveSelected(-1)); RibbonContent.Add(up); var down = Btn("Write.Home.Down", "↓ Block"); down.Invoked += (_, _) => Apply(value => value.MoveSelected(1)); RibbonContent.Add(down); var delete = Btn("Write.Home.Delete", "Delete block", ButtonVariant.Danger); delete.Invoked += (_, _) => Apply(value => value.DeleteSelected()); RibbonContent.Add(delete);
    }

    private void Insert() { AddInsert("Paragraph", NotesBlockKind.Paragraph); AddInsert("Heading 1", NotesBlockKind.Heading, style: "heading-1"); AddInsert("Heading 2", NotesBlockKind.Heading, style: "heading-2"); AddInsert("Quote", NotesBlockKind.Quote); AddInsert("Code", NotesBlockKind.Code); AddInsert("Bullets", NotesBlockKind.List, NotesListKind.Bulleted); AddInsert("Numbering", NotesBlockKind.List, NotesListKind.Numbered); AddInsert("Checklist", NotesBlockKind.List, NotesListKind.Checklist); AddInsert("Table 3×3", NotesBlockKind.Table); var image = Btn("Write.Insert.Image", "Image"); image.Invoked += (_, _) => ImageRequested?.Invoke(this, EventArgs.Empty); RibbonContent.Add(image); AddInsert("Equation", NotesBlockKind.Equation); AddInsert("Divider", NotesBlockKind.Divider); }
    private void AddInsert(string label, NotesBlockKind kind, NotesListKind listKind = NotesListKind.Bulleted, string? style = null) { var button = Btn("Write.Insert." + label.Replace(" ", string.Empty, StringComparison.Ordinal), label); button.Invoked += (_, _) => { if (_editor is null) return; var block = _editor.InsertBlock(kind, listKind); if (style is not null) { _editor.SelectBlock(block.Id); _editor.ApplyStyle(style); } RebuildAll(); }; RibbonContent.Add(button); }

    private void Layout()
    {
        var editor = _editor!; var a4 = Btn("Write.Layout.A4", "A4"); a4.Invoked += (_, _) => Apply(value => { value.SetPagePreset("A4"); return true; }); RibbonContent.Add(a4); var letter = Btn("Write.Layout.Letter", "Letter"); letter.Invoked += (_, _) => Apply(value => { value.SetPagePreset("Letter"); return true; }); RibbonContent.Add(letter); foreach (var orientation in new[] { "Portrait", "Landscape" }) { var button = Btn("Write.Layout." + orientation, orientation, editor.Document.PageSetup.Orientation.Equals(orientation, StringComparison.OrdinalIgnoreCase) ? ButtonVariant.Primary : ButtonVariant.Tertiary); button.Invoked += (_, _) => Apply(value => { value.SetOrientation(orientation); return true; }); RibbonContent.Add(button); } RibbonContent.Add(NumberField("Write.Layout.Margins", "Margins in points", editor.Document.PageSetup.MarginTopPoints, editor.SetMargins, 96)); var numbers = new Toggle { Name = "Write.Layout.PageNumbers", IsChecked = editor.Document.PageSetup.ShowPageNumbers }; numbers.Accessibility.AccessibleName = "Show page numbers"; numbers.CheckedChanged += (_, _) => { if (!_suppress) editor.SetPageNumbers(numbers.IsChecked); }; RibbonContent.Add(numbers); foreach (var mode in new[] { NotesLayoutMode.Paginated, NotesLayoutMode.Continuous }) { var button = Btn("Write.Layout.Mode." + mode, mode.ToString(), editor.Document.LayoutMode == mode ? ButtonVariant.Primary : ButtonVariant.Tertiary); button.Invoked += (_, _) => Apply(value => { value.SetLayout(mode); return true; }); RibbonContent.Add(button); } RibbonContent.Add(Caption($"{editor.Document.PageSetup.WidthPoints:0} × {editor.Document.PageSetup.HeightPoints:0} pt"));
    }

    private void Review()
    {
        var editor = _editor!; var stats = editor.Statistics; RibbonContent.Add(Caption($"{stats.Words} words · {stats.Characters} chars · {stats.Paragraphs} paragraphs · {stats.ReadingMinutes} min")); var find = Field("Write.Review.Find", "Find text", "Find"); find.Text = _find; find.SetValue(HavenProperties.Width, HavenLength.Px(140)); find.Invalidated += (_, _) => _find = find.Text; RibbonContent.Add(find); var replace = Field("Write.Review.Replace", "Replacement text", "Replace with"); replace.Text = _replace; replace.SetValue(HavenProperties.Width, HavenLength.Px(140)); replace.Invalidated += (_, _) => _replace = replace.Text; RibbonContent.Add(replace); var findButton = Btn("Write.Review.FindButton", "Find"); findButton.Invoked += (_, _) => SetStatus(editor.Find(_find).Count + " match(es)"); RibbonContent.Add(findButton); var replaceAll = Btn("Write.Review.ReplaceAll", "Replace all"); replaceAll.Invoked += (_, _) => { var count = editor.ReplaceAll(_find, _replace); RebuildAll(); SetStatus($"Replaced {count} match(es)"); }; RibbonContent.Add(replaceAll);
        var comment = Field("Write.Review.Comment", "Comment", "Comment on selected block"); comment.Text = _comment; comment.SetValue(HavenProperties.Width, HavenLength.Px(190)); comment.Invalidated += (_, _) => _comment = comment.Text; RibbonContent.Add(comment); var addComment = Btn("Write.Review.AddComment", "Add comment"); addComment.Invoked += (_, _) => { editor.AddComment(_comment); _comment = string.Empty; RebuildAll(); }; RibbonContent.Add(addComment);
        var sourceTitle = Field("Write.Review.SourceTitle", "Source title", "Source title"); sourceTitle.Text = _citationTitle; sourceTitle.SetValue(HavenProperties.Width, HavenLength.Px(150)); sourceTitle.Invalidated += (_, _) => _citationTitle = sourceTitle.Text; RibbonContent.Add(sourceTitle); var authors = Field("Write.Review.Authors", "Source authors", "Authors"); authors.Text = _citationAuthors; authors.SetValue(HavenProperties.Width, HavenLength.Px(120)); authors.Invalidated += (_, _) => _citationAuthors = authors.Text; RibbonContent.Add(authors); var url = Field("Write.Review.Url", "Source URL", "https://"); url.Text = _citationUrl; url.SetValue(HavenProperties.Width, HavenLength.Px(150)); url.Invalidated += (_, _) => _citationUrl = url.Text; RibbonContent.Add(url); var cite = Btn("Write.Review.AddSource", "Add source"); cite.Invoked += (_, _) => { editor.AddCitation(_citationTitle, _citationAuthors, _citationUrl); _citationTitle = _citationAuthors = _citationUrl = string.Empty; RebuildAll(); }; RibbonContent.Add(cite); RibbonContent.Add(Caption($"Comments {editor.Document.Comments.Count} · Sources {editor.Document.Citations.Count} · Revisions {editor.Document.Revisions.Count}"));
    }

    private void RebuildDocument()
    {
        _blockInputs.Clear(); DocumentHost.Children.ToList().ForEach(child => child.Parent?.Remove(child)); if (_editor is null) return; var setup = _editor.Document.PageSetup; var width = Math.Clamp(setup.WidthPoints * .92, 520, 900); var margin = Math.Clamp(setup.MarginLeftPoints * .75, 28, 100); DocumentHost.SetValue(HavenProperties.MaxWidth, HavenLength.Px(width)); DocumentHost.SetValue(HavenProperties.Padding, HavenThickness.Parse($"{margin:0}px")); foreach (var section in _editor.Document.Sections) foreach (var page in section.Pages) foreach (var block in page.Blocks.OrderBy(value => value.Order)) DocumentHost.Add(Block(block));
    }

    private HavenElement Block(NotesBlock block)
    {
        var card = new Container { Name = $"Write.Word.Block.{block.Id:N}", Layout = HavenLayout.Vertical }; card.SetValue(HavenProperties.Gap, HavenLength.Px(5)); card.SetValue(HavenProperties.Padding, HavenThickness.Parse("5px")); if (_editor?.SelectedBlockId == block.Id) { card.SetValue(HavenProperties.BorderColor, "AccentSecondary"); card.SetValue(HavenProperties.BorderWidth, HavenLength.Px(1)); card.SetValue(HavenProperties.Radius, HavenCornerRadius.Uniform(HavenLength.Px(6))); } var header = Bar($"Write.Word.Block.{block.Id:N}.Header", 0); var select = Btn($"Write.Word.Block.{block.Id:N}.Select", Label(block), _editor?.SelectedBlockId == block.Id ? ButtonVariant.Primary : ButtonVariant.Ghost); select.Invoked += (_, _) => { _editor?.SelectBlock(block.Id); RebuildAll(); }; header.Add(select); if (block.Runs.Count > 1) header.Add(Caption($"{block.Runs.Count} formatted runs · ribbon targets run at caret")); card.Add(header); switch (block.Kind) { case NotesBlockKind.Paragraph or NotesBlockKind.Heading or NotesBlockKind.Quote or NotesBlockKind.Code: card.Add(TextBlock(block)); break; case NotesBlockKind.List: ListBlock(card, block); break; case NotesBlockKind.Table: TableBlock(card, block); break; case NotesBlockKind.Equation: EquationBlock(card, block); break; case NotesBlockKind.Image or NotesBlockKind.Audio or NotesBlockKind.Video: MediaBlock(card, block); break; case NotesBlockKind.Divider: var line = new Container(); line.SetValue(HavenProperties.Height, HavenLength.Px(1)); line.SetValue(HavenProperties.Background, "Border"); card.Add(line); break; default: card.Add(Caption($"{block.Kind} is preserved in the native document and remains available to its specialist editor.")); break; } return card;
    }

    private Input TextBlock(NotesBlock block)
    {
        var input = Field($"Write.Word.Block.{block.Id:N}.Input", block.Kind + " text", block.Kind == NotesBlockKind.Heading ? "Heading" : "Type here…"); input.Multiline = true; input.Text = block.Runs.Count > 0 ? string.Concat(block.Runs.Select(run => run.Text)) : block.PlainText; input.SetValue(HavenProperties.MinHeight, HavenLength.Px(block.Kind == NotesBlockKind.Heading ? 56 : 84)); var run = block.Runs.FirstOrDefault(); if (run is not null) { input.SetValue(HavenProperties.FontFamily, run.FontFamily); input.SetValue(HavenProperties.FontSize, run.FontSize); input.SetValue(HavenProperties.FontWeight, run.Bold ? 700 : 400); } else if (block.Kind == NotesBlockKind.Heading) { input.SetValue(HavenProperties.FontSize, 26d); input.SetValue(HavenProperties.FontWeight, 700); } if (block.Kind == NotesBlockKind.Code) input.SetValue(HavenProperties.FontFamily, "Cascadia Mono"); input.Invalidated += (_, _) => { if (_suppress || _editor is null) return; _editor.SelectBlock(block.Id, input.CaretIndex); _editor.ReplaceSelectedText(input.Text, input.CaretIndex); }; _blockInputs[block.Id] = input; return input;
    }

    private void ListBlock(Container card, NotesBlock block)
    {
        if (block.List is null) return; var type = Choice($"Write.Word.List.{block.Id:N}.Type", "List type", Enum.GetNames<NotesListKind>(), (int)block.List.Kind); type.SelectionChanged += (_, _) => { if (_editor is null || type.SelectedItem is null || !Enum.TryParse<NotesListKind>(type.SelectedItem, out var kind)) return; _editor.SelectBlock(block.Id); _editor.SetListKind(kind); RebuildAll(); }; card.Add(type); foreach (var item in block.List.Items) { var row = Bar($"Write.Word.List.{item.Id:N}", 0); if (block.List.Kind == NotesListKind.Checklist) { var check = new Toggle { IsChecked = item.Checked }; check.Accessibility.AccessibleName = "Checklist item complete"; check.CheckedChanged += (_, _) => { _editor?.SelectBlock(block.Id); _editor?.ToggleListItem(item.Id, check.IsChecked); }; row.Add(check); } var input = Field($"Write.Word.List.{item.Id:N}.Text", "List item", "List item"); input.Text = item.Text; input.SetValue(HavenProperties.Width, HavenLength.Px(440)); input.Invalidated += (_, _) => { if (_suppress) return; _editor?.SelectBlock(block.Id); _editor?.UpdateListItem(item.Id, input.Text); }; row.Add(input); row.Add(NumberField($"Write.Word.List.{item.Id:N}.Level", "Nesting level", item.Level, value => { _editor?.SelectBlock(block.Id); _editor?.SetListItemLevel(item.Id, (int)value); }, 68)); card.Add(row); } var add = Btn($"Write.Word.List.{block.Id:N}.Add", "+ List item"); add.Invoked += (_, _) => { _editor?.SelectBlock(block.Id); _editor?.AddListItem(); RebuildAll(); }; card.Add(add);
    }

    private void TableBlock(Container card, NotesBlock block)
    {
        if (block.Table is null || block.Table.Rows.Count == 0) return; var controls = Bar($"Write.Word.Table.{block.Id:N}.Controls", 0); foreach (var pair in new[] { ("+ Row", 1), ("− Row", 2), ("+ Column", 3), ("− Column", 4) }) { var button = Btn($"Write.Word.Table.{block.Id:N}.{pair.Item2}", pair.Item1); button.Invoked += (_, _) => { if (_editor is null) return; _editor.SelectBlock(block.Id); switch (pair.Item2) { case 1: _editor.AddTableRow(); break; case 2: _editor.RemoveTableRow(); break; case 3: _editor.AddTableColumn(); break; case 4: _editor.RemoveTableColumn(); break; } RebuildAll(); }; controls.Add(button); } card.Add(controls); var columns = block.Table.Rows.Max(row => row.Cells.Count); var grid = new Container { Name = $"Write.Word.Table.{block.Id:N}", Layout = HavenLayout.Grid, Columns = string.Join(' ', Enumerable.Repeat("1fr", columns)), Rows = string.Join(' ', Enumerable.Repeat("Auto", block.Table.Rows.Count)) }; grid.SetValue(HavenProperties.Gap, HavenLength.Px(3)); for (var row = 0; row < block.Table.Rows.Count; row++) for (var column = 0; column < block.Table.Rows[row].Cells.Count; column++) { var cell = block.Table.Rows[row].Cells[column]; var input = Field($"Write.Word.Table.Cell.{cell.Id:N}", $"Table cell {row + 1}, {column + 1}", "Cell"); input.Text = cell.Text; input.Multiline = true; input.SetValue(HavenProperties.Row, row); input.SetValue(HavenProperties.Column, column); input.SetValue(HavenProperties.MinHeight, HavenLength.Px(48)); if (row == 0 && block.Table.HeaderRow) input.SetValue(HavenProperties.FontWeight, 700); input.Invalidated += (_, _) => { if (_suppress) return; _editor?.SelectBlock(block.Id); _editor?.UpdateTableCell(cell.Id, input.Text); }; grid.Add(input); } card.Add(grid);
    }

    private void EquationBlock(Container card, NotesBlock block) { if (block.Equation is null) return; var source = Field($"Write.Word.Equation.{block.Id:N}.Source", "Equation source", "LaTeX"); source.Text = block.Equation.Source; source.Multiline = true; source.SetValue(HavenProperties.FontFamily, "Cascadia Mono"); var alt = Field($"Write.Word.Equation.{block.Id:N}.Alt", "Equation accessible description", "Accessible description"); alt.Text = block.Equation.AccessibleAlternative; alt.Multiline = true; void Update() { if (_suppress || _editor is null) return; _editor.SelectBlock(block.Id); _editor.UpdateEquation(source.Text, alt.Text); } source.Invalidated += (_, _) => Update(); alt.Invalidated += (_, _) => Update(); card.Add(source); card.Add(alt); }
    private void MediaBlock(Container card, NotesBlock block) { if (block.Media is null) return; card.Add(Caption($"{block.Media.OriginalName} · {block.Media.MediaType} · {block.Media.Width:0}×{block.Media.Height:0}")); var alt = Field($"Write.Word.Media.{block.Id:N}.Alt", "Image alternative text", "Alternative text"); alt.Text = block.Media.AltText; var caption = Field($"Write.Word.Media.{block.Id:N}.Caption", "Image caption", "Caption"); caption.Text = block.Media.Caption; var wrapItems = new[] { "Inline", "Square", "Tight", "Behind text", "In front of text" }; var wrap = Choice($"Write.Word.Media.{block.Id:N}.Wrap", "Text wrapping", wrapItems, Math.Max(0, Array.IndexOf(wrapItems, block.Media.Wrapping))); void Update() { if (_suppress || _editor is null) return; _editor.SelectBlock(block.Id); _editor.UpdateMedia(alt.Text, caption.Text, wrap.SelectedItem ?? "Inline"); } alt.Invalidated += (_, _) => Update(); caption.Invalidated += (_, _) => Update(); wrap.SelectionChanged += (_, _) => Update(); card.Add(alt); card.Add(caption); card.Add(wrap); }

    private HavenButton Format(string name, string label, bool selected, WriteCharacterFormat format) { var button = Btn(name, label, selected ? ButtonVariant.Primary : ButtonVariant.Tertiary); button.SetValue(HavenProperties.FontWeight, 800); button.Invoked += (_, _) => Apply(editor => { editor.ToggleCharacter(format); return true; }); return button; }
    private Input NumberField(string name, string accessible, double value, Action<double> apply, double width) { var input = Field(name, accessible, value.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture)); input.Text = value.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture); input.SetValue(HavenProperties.Width, HavenLength.Px(width)); input.Invalidated += (_, _) => { if (_suppress || !double.TryParse(input.Text, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var parsed)) return; apply(parsed); }; return input; }
    private void Apply(Func<WriteDocumentEditor, bool> action) { if (_editor is null || !action(_editor)) return; RebuildAll(); }
    private void UpdateStats() { if (_editor is null) return; var stats = _editor.Statistics; StatusText.Content = $"{stats.Words} words · {stats.Characters} characters · {stats.ReadingMinutes} min read · autosave on"; }
    private static string Label(NotesBlock block) => block.Kind switch { NotesBlockKind.Heading => block.StyleId == "heading-2" ? "Heading 2" : "Heading 1", NotesBlockKind.List when block.List is not null => block.List.Kind + " list", _ => block.Kind.ToString() };
    private static Container Bar(string name, int row) { var bar = new Container { Name = name, Layout = HavenLayout.Horizontal }; bar.SetValue(HavenProperties.Row, row); bar.SetValue(HavenProperties.Gap, HavenLength.Px(6)); bar.SetValue(HavenProperties.Overflow, HavenOverflow.Scroll); bar.SetValue(HavenProperties.Padding, HavenThickness.Parse("4px 18px")); return bar; }
    private static HavenButton Btn(string name, string label, ButtonVariant variant = ButtonVariant.Tertiary) { var button = new HavenButton { Name = name, Content = label, Variant = variant }; button.Accessibility.AccessibleName = label; button.SetValue(HavenProperties.MinHeight, HavenLength.Px(34)); return button; }
    private static Input Field(string name, string accessible, string placeholder) { var input = new Input { Name = name, Placeholder = placeholder }; input.Accessibility.AccessibleName = accessible; input.SetValue(HavenProperties.MinHeight, HavenLength.Px(40)); return input; }
    private static Select Choice(string name, string accessible, IReadOnlyList<string> items, int index) { var select = new Select { Name = name, Items = items, SelectedIndex = index }; select.Accessibility.AccessibleName = accessible; select.SetValue(HavenProperties.MinWidth, HavenLength.Px(116)); return select; }
    private static HavenText Caption(string text) { var value = new HavenText(text) { Level = TextLevel.Caption }; value.SetValue(HavenProperties.Foreground, "TextSecondary"); return value; }
    public void Dispose() { if (_disposed) return; _disposed = true; TitleInput.Invalidated -= OnTitleInvalidated; if (_editor is not null) _editor.Changed -= OnEditorChanged; PreviousRequested = null; NextRequested = null; NewRequested = null; ImportRequested = null; ExportRequested = null; SaveRequested = null; ImageRequested = null; DocumentChanged = null; }
}
