namespace Haven.Core;

/// <summary>
/// Canonical reusable foundations. Maturity is explicit: a registry entry is
/// discovery metadata, never proof that Clause 85.47 is feature-complete.
/// </summary>
public static class TemplateRegistryCatalog
{
    public static IReadOnlyList<GenUiTemplateDefinition> BuiltIns { get; } =
    [
        Foundation("calculator", "Calculator", "Deterministic arithmetic utility with structured result events.", "Utility",
            ["calculator", "maths", "deterministic"], "haven.template.calculator", GenUiTemplateScale.FullExperience,
            ["chat", "study", "data"], ["expression"], ["result", "error"], [GenUiEventType.TextSubmitted, GenUiEventType.ValidationRequested],
            ["HavenForm", "HavenTextInput", "HavenButton", "HavenStatus"], deterministic: true, maturity: GenUiTemplateMaturity.Preview),
        Foundation("structured-form", "Structured Form", "Validated typed inputs, field errors, submit and reset.", "Input",
            ["form", "survey", "poll", "input"], "haven.template.form", GenUiTemplateScale.Pattern,
            ["chat", "plan", "tasks"], ["schema", "initialValues"], ["values", "validationErrors"], [GenUiEventType.FormSubmitted, GenUiEventType.ValidationRequested],
            ["HavenForm", "HavenTextInput", "HavenSelect", "HavenToggle", "HavenButton"], deterministic: true),
        Foundation("checklist", "Checklist", "Ordered checklist backed by an owning App or thread state.", "Planning",
            ["checklist", "tasks", "plan"], "haven.template.checklist", GenUiTemplateScale.FullExperience,
            ["plan", "tasks", "chat"], ["items"], ["items", "completion"], [GenUiEventType.ToggleChanged, GenUiEventType.ItemReordered, GenUiEventType.ItemCreated],
            ["HavenList", "HavenToggle", "HavenTextInput", "HavenButton"], deterministic: true, ownership: GenUiStateOwnership.App),
        Foundation("data-grid", "Data Grid", "Sortable, filterable structured table with incremental row updates.", "Data",
            ["table", "grid", "data", "comparison"], "haven.template.data-grid", GenUiTemplateScale.Pattern,
            ["data", "browse", "plan"], ["columns", "rows"], ["selection", "sort", "filter"], [GenUiEventType.ItemSelected, GenUiEventType.FilterChanged],
            ["HavenTable", "HavenTextInput", "HavenSelect"], deterministic: true),
        Foundation("dashboard", "Dashboard", "Composable KPI, status, chart, table and action regions.", "Data",
            ["dashboard", "kpi", "monitor"], "haven.template.dashboard", GenUiTemplateScale.Composition,
            ["dashboard", "data", "tasks"], ["panels", "dataSources"], ["selection", "filters"], [GenUiEventType.ItemSelected, GenUiEventType.FilterChanged],
            ["HavenGrid", "HavenCard", "HavenStatus", "HavenChart", "HavenTable"], deterministic: true),
        Foundation("assessment", "Assessment", "Question, answer, marking, score and feedback state.", "Learning",
            ["quiz", "test", "assessment", "typed-answer"], "haven.template.assessment", GenUiTemplateScale.FullExperience,
            ["study"], ["questions", "markScheme"], ["answers", "score"], [GenUiEventType.AnswerRecorded, GenUiEventType.ActivityCompleted],
            ["HavenForm", "HavenCard", "HavenProgress", "HavenStatus"], agent: GenUiAgentInteractionMode.Required),
        Foundation("card-deck", "Card Deck", "Flashcards with reveal, rating, confidence and progress.", "Learning",
            ["flashcards", "retrieval", "confidence"], "haven.template.card-deck", GenUiTemplateScale.FullExperience,
            ["study"], ["cards"], ["responses", "confidence", "progress"], [GenUiEventType.AnswerRecorded, GenUiEventType.ConfidenceRecorded],
            ["HavenCard", "HavenButton", "HavenProgress"], deterministic: true, agent: GenUiAgentInteractionMode.Optional),
        Foundation("whiteboard", "Whiteboard / Scratchboard", "Structured semantic board foundation; production maturity requires the full Clause 85.47.2 baseline.", "Learning",
            ["whiteboard", "scratchboard", "ink", "diagram"], "haven.template.whiteboard", GenUiTemplateScale.FullExperience,
            ["study", "imagine"], ["objects", "tools", "viewport"], ["objects", "selection", "history"], [GenUiEventType.ItemCreated, GenUiEventType.ItemEdited, GenUiEventType.ItemDeleted, GenUiEventType.ViewportChanged],
            ["HavenCanvas", "HavenToolbar", "HavenSelect", "HavenSlider"], agent: GenUiAgentInteractionMode.Required),
        Foundation("graph", "Graph", "Expression, series, viewport, point and accessible data-table visualisation.", "Visualisation",
            ["graph", "chart", "function", "plot"], "haven.template.graph", GenUiTemplateScale.FullExperience,
            ["study", "data", "chat"], ["expressions", "series", "viewport"], ["points", "viewport"], [GenUiEventType.ItemSelected, GenUiEventType.ViewportChanged, GenUiEventType.TextSubmitted],
            ["HavenGraph", "HavenTable", "HavenTextInput", "HavenToolbar"], agent: GenUiAgentInteractionMode.Optional),
        Foundation("document-workspace", "Document Workspace", "Structured document, outline, sources and review regions.", "Content",
            ["document", "notes", "report", "outline"], "haven.template.document-workspace", GenUiTemplateScale.Composition,
            ["present", "study", "browse"], ["document", "outline", "sources"], ["document", "selection"], [GenUiEventType.ItemEdited, GenUiEventType.ItemSelected],
            ["HavenSplitView", "HavenMarkdown", "HavenList", "HavenToolbar"], ownership: GenUiStateOwnership.App),
        Foundation("code-workspace", "Code Workspace", "Repository tree, editor, diff, build/test and log composition.", "Development",
            ["code", "repository", "diff", "tests", "logs"], "haven.template.code-workspace", GenUiTemplateScale.Composition,
            ["studio"], ["workspace", "selection"], ["files", "diff", "runResults"], [GenUiEventType.ItemSelected, GenUiEventType.ActionInvoked],
            ["HavenSplitView", "HavenTabs", "HavenList", "HavenStatus"], ["workspace"], ["read-file", "write-file", "run-tests"], ownership: GenUiStateOwnership.App),
        Foundation("research-results", "Research Results", "Sources, excerpts, comparison and provenance-aware selection.", "Research",
            ["research", "sources", "search", "citations"], "haven.template.research-results", GenUiTemplateScale.FullExperience,
            ["browse", "study", "present"], ["query", "sources"], ["selection", "citations"], [GenUiEventType.SearchSubmitted, GenUiEventType.ItemSelected],
            ["HavenTextInput", "HavenList", "HavenCard", "HavenTable"], ["browser"], ["web-search"], network: true, offline: false, ownership: GenUiStateOwnership.App),
        Foundation("task-list", "Task List", "Real task state, progress, approvals, stop and result controls.", "Execution",
            ["tasks", "execution", "approval", "progress"], "haven.template.task-list", GenUiTemplateScale.FullExperience,
            ["tasks", "plan"], ["tasks"], ["tasks", "results"], [GenUiEventType.ActionInvoked, GenUiEventType.ApprovalAccepted, GenUiEventType.ApprovalDenied, GenUiEventType.CancelRequested],
            ["HavenList", "HavenProgress", "HavenButton", "HavenStatus"], ["tasks"], ["run-task", "edit-task"], ownership: GenUiStateOwnership.App),
        Foundation("workflow", "Workflow", "Steps, conditions, approvals, execution and recovery state.", "Execution",
            ["workflow", "automation", "rules", "wizard"], "haven.template.workflow", GenUiTemplateScale.FullExperience,
            ["tasks", "studio"], ["steps", "rules"], ["state", "results"], [GenUiEventType.StepCompleted, GenUiEventType.ApprovalAccepted, GenUiEventType.RetryRequested],
            ["HavenWizard", "HavenList", "HavenForm", "HavenStatus"], ["tasks"], ["create-automation", "run-task"], ownership: GenUiStateOwnership.App)
    ];

    private static GenUiTemplateDefinition Foundation(
        string key,
        string name,
        string description,
        string category,
        IReadOnlyList<string> tags,
        string implementation,
        GenUiTemplateScale scale,
        IReadOnlyList<string> apps,
        IReadOnlyList<string> inputs,
        IReadOnlyList<string> outputs,
        IReadOnlyList<GenUiEventType> events,
        IReadOnlyList<string> primitives,
        IReadOnlyList<string>? services = null,
        IReadOnlyList<string>? capabilities = null,
        bool network = false,
        bool offline = true,
        bool deterministic = false,
        GenUiAgentInteractionMode agent = GenUiAgentInteractionMode.Optional,
        GenUiStateOwnership ownership = GenUiStateOwnership.Thread,
        GenUiTemplateMaturity maturity = GenUiTemplateMaturity.Foundation) => new(
        GuidUtility.FromStableName("haven.template." + key), key, "1.0.0", name, description, category, tags,
        implementation, scale, apps, apps, inputs, outputs, events,
        ["title", "accent", "layout", "emptyState"],
        ["Stable typed input matching the declared template contract."],
        events.Select(item => item.ToString()).ToArray(),
        primitives, services ?? [], capabilities ?? [],
        deterministic ? [] : [ToolCapability.Text, ToolCapability.StructuredOutput],
        network, offline, CapabilityPlatform.All,
        "Keyboard reachable, labelled controls, focus order, scalable text, high-contrast tokens, and non-visual status alternatives are required.",
        SupportsPersistence: true, SupportsThreadScope: true, SupportsUserApps: true,
        SupportsMiniApps: scale is GenUiTemplateScale.Primitive or GenUiTemplateScale.Pattern,
        SupportsEmbedding: true, agent, deterministic, ownership, maturity,
        IsBuiltIn: true, IsEnabled: true, UpdatedAt: DateTimeOffset.UnixEpoch);
}
