using System.Text.Json;
using Haven.Core;

namespace Haven.Application;

/// <summary>
/// Builds a GenUiDocument from an inline HavenUI component tree
/// generated by the model when no registered template fits.
/// Registers local action handlers so interactive components actually work.
/// </summary>
public sealed class CustomTemplateRuntime
{
    private readonly GenUiLocalActionRegistry _localActions;
    private readonly GenUiInstanceStore _instances;

    public CustomTemplateRuntime(GenUiLocalActionRegistry localActions, GenUiInstanceStore instances)
    {
        _localActions = localActions;
        _instances = instances;
    }

    public GenUiDocument Create(Guid threadId, string appKey, IReadOnlyDictionary<string, JsonElement> inputs)
    {
        var title = inputs.TryGetValue("title", out var t) && t.ValueKind == JsonValueKind.String
            ? t.GetString() ?? "Custom UI" : "Custom UI";

        var instanceId = Guid.NewGuid();
        var root = inputs.TryGetValue("components", out var componentsEl) && componentsEl.ValueKind == JsonValueKind.Array
            ? BuildComponentTree(componentsEl)
            : new GenUiComponent("custom.empty", "HavenText",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["text"] = JsonSerializer.SerializeToElement("No components provided")
                }, [], []);

        // Find or add a status component for action feedback
        var statusId = FindStatusComponentId(root) ?? "custom.status";
        if (FindStatusComponentId(root) is null)
        {
            // Add a status component if none exists
            var children = root.Children.ToList();
            children.Add(new GenUiComponent(statusId, "HavenStatus",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["text"] = JsonSerializer.SerializeToElement("Ready"),
                    ["automationName"] = JsonSerializer.SerializeToElement("Status")
                }, [], []));
            root = root with { Children = children };
        }

        // Register generic action handlers for all actions in this custom template
        RegisterActionHandlers(instanceId, root, statusId);

        var origin = new GenUiOrigin(threadId, appKey, null, instanceId);
        return new GenUiDocument(
            Guid.NewGuid(),
            GenerativeUiContractValidator.CurrentContractVersion,
            origin,
            title,
            appKey,
            root,
            new Dictionary<string, JsonElement>(StringComparer.Ordinal),
            DateTimeOffset.UtcNow);
    }

    private void RegisterActionHandlers(Guid instanceId, GenUiComponent root, string statusId)
    {
        var actionIds = CollectActionIds(root);
        foreach (var actionId in actionIds)
        {
            _localActions.RegisterOrReplace(actionId, (evt, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                var now = DateTimeOffset.UtcNow;
                var patches = new List<GenUiStatePatch>();

                // Capture the value from the event and patch the source component
                if (evt.Value is { ValueKind: not JsonValueKind.Null and not JsonValueKind.Undefined })
                {
                    patches.Add(new GenUiStatePatch(
                        Guid.NewGuid(), instanceId, GenUiPatchOperation.Replace,
                        evt.ComponentId, "value", evt.Value, now));
                }

                // Patch state with all captured input values from the payload
                if (evt.StructuredPayload.TryGetProperty("values", out var values) && values.ValueKind == JsonValueKind.Object)
                {
                    foreach (var val in values.EnumerateObject())
                    {
                        patches.Add(new GenUiStatePatch(
                            Guid.NewGuid(), instanceId, GenUiPatchOperation.Replace,
                            "state", val.Name, val.Value.Clone(), now));
                    }
                }

                // Update the status component with action feedback
                patches.Add(new GenUiStatePatch(
                    Guid.NewGuid(), instanceId, GenUiPatchOperation.Replace,
                    statusId, "text",
                    JsonSerializer.SerializeToElement($"Action '{actionId}' completed"), now));

                return Task.FromResult(GenerativeUiEventRouter.Result(
                    evt, GenUiActionStatus.Completed,
                    $"Action '{actionId}' processed.",
                    JsonSerializer.SerializeToElement(new { action = actionId, componentId = evt.ComponentId }),
                    patches));
            });
        }
    }

    private static string? FindStatusComponentId(GenUiComponent component)
    {
        if (component.ComponentType == "HavenStatus") return component.ComponentId;
        foreach (var child in component.Children)
        {
            var found = FindStatusComponentId(child);
            if (found is not null) return found;
        }
        return null;
    }

    private static HashSet<string> CollectActionIds(GenUiComponent component)
    {
        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var action in component.Actions)
            ids.Add(action.ActionId);
        foreach (var child in component.Children)
            foreach (var id in CollectActionIds(child))
                ids.Add(id);
        return ids;
    }

    private static GenUiComponent BuildComponentTree(JsonElement componentsEl)
    {
        var children = componentsEl.EnumerateArray()
            .Where(el => el.ValueKind == JsonValueKind.Object)
            .Select(BuildComponent)
            .ToArray();

        // Wrap in a workspace if multiple root components
        if (children.Length > 1)
            return new GenUiComponent("custom.workspace", "HavenStack",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["spacing"] = JsonSerializer.SerializeToElement(10)
                }, [], children);

        return children.Length == 1 ? children[0] :
            new GenUiComponent("custom.empty", "HavenText",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["text"] = JsonSerializer.SerializeToElement("Empty")
                }, [], []);
    }

    private static GenUiComponent BuildComponent(JsonElement el)
    {
        var id = el.TryGetProperty("id", out var idEl) && idEl.ValueKind == JsonValueKind.String
            ? idEl.GetString() ?? Guid.NewGuid().ToString("N")[..8]
            : Guid.NewGuid().ToString("N")[..8];

        var type = el.TryGetProperty("type", out var typeEl) && typeEl.ValueKind == JsonValueKind.String
            ? typeEl.GetString() ?? "HavenText" : "HavenText";

        // Validate component type against trusted vocabulary
        if (!GenerativeUiContractValidator.TrustedComponentTypes.Contains(type))
            type = "HavenText"; // Fallback to safe type

        var props = new Dictionary<string, JsonElement>(StringComparer.Ordinal);
        if (el.TryGetProperty("props", out var propsEl) && propsEl.ValueKind == JsonValueKind.Object)
        {
            foreach (var prop in propsEl.EnumerateObject())
            {
                if (!GenerativeUiContractValidator.ValidatePropertyName(prop.Name))
                    continue;
                props[prop.Name] = prop.Value.Clone();
            }
        }

        var actions = new List<GenUiActionBinding>();
        if (el.TryGetProperty("actions", out var actionsEl) && actionsEl.ValueKind == JsonValueKind.Array)
        {
            foreach (var action in actionsEl.EnumerateArray())
            {
                if (action.ValueKind != JsonValueKind.Object) continue;
                var actionId = action.TryGetProperty("id", out var aid) && aid.ValueKind == JsonValueKind.String
                    ? aid.GetString() ?? "" : "";
                if (string.IsNullOrWhiteSpace(actionId)) continue;
                actions.Add(new GenUiActionBinding(
                    actionId,
                    GenUiRouteKind.Local,
                    actionId,
                    CapabilityRiskClass.Low,
                    false));
            }
        }

        var children = new List<GenUiComponent>();
        if (el.TryGetProperty("children", out var childrenEl) && childrenEl.ValueKind == JsonValueKind.Array)
        {
            foreach (var child in childrenEl.EnumerateArray())
            {
                if (child.ValueKind == JsonValueKind.Object)
                    children.Add(BuildComponent(child));
            }
        }

        return new GenUiComponent(id, type, props, actions, children);
    }
}
