using System.Text.Json;
using Haven.Core;

namespace Haven.Application;

/// <summary>
/// Builds a GenUiDocument from an inline HavenUI component tree generated by
/// the model when no registered template fits. Custom interactions remain
/// declarative: actions may request bounded property/state patches but cannot
/// supply executable code.
/// </summary>
public sealed class CustomTemplateRuntime
{
    private readonly GenUiLocalActionRegistry _localActions;
    private readonly GenUiInstanceStore _instances;

    public CustomTemplateRuntime(GenUiLocalActionRegistry localActions, GenUiInstanceStore instances)
    {
        _localActions = localActions;
        _instances = instances;
    }

    public GenUiDocument Create(Guid threadId, string appKey, IReadOnlyDictionary<string, JsonElement> inputs)
    {
        var title = inputs.TryGetValue("title", out var t) && t.ValueKind == JsonValueKind.String
            ? t.GetString() ?? "Custom UI" : "Custom UI";

        var instanceId = Guid.NewGuid();
        var actionDefinitions = new Dictionary<string, CustomActionDefinition>(StringComparer.Ordinal);
        var root = inputs.TryGetValue("components", out var componentsEl) && componentsEl.ValueKind == JsonValueKind.Array
            ? BuildComponentTree(componentsEl, actionDefinitions)
            : new GenUiComponent("custom.empty", "HavenText",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["text"] = JsonSerializer.SerializeToElement("No components provided")
                }, [], []);

        var statusId = FindStatusComponentId(root) ?? "custom.status";
        if (FindStatusComponentId(root) is null)
        {
            var children = root.Children.ToList();
            children.Add(new GenUiComponent(statusId, "HavenStatus",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["text"] = JsonSerializer.SerializeToElement("Ready"),
                    ["automationName"] = JsonSerializer.SerializeToElement("Status")
                }, [], []));
            root = root with { Children = children };
        }

        RegisterActionHandlers(instanceId, root, statusId, actionDefinitions);

        var origin = new GenUiOrigin(threadId, appKey, null, instanceId);
        return new GenUiDocument(
            Guid.NewGuid(),
            GenerativeUiContractValidator.CurrentContractVersion,
            origin,
            title,
            appKey,
            root,
            new Dictionary<string, JsonElement>(StringComparer.Ordinal),
            DateTimeOffset.UtcNow);
    }

    private void RegisterActionHandlers(
        Guid instanceId,
        GenUiComponent root,
        string statusId,
        IReadOnlyDictionary<string, CustomActionDefinition> actionDefinitions)
    {
        var componentIds = CollectComponentIds(root);
        foreach (var actionId in CollectActionIds(root))
        {
            actionDefinitions.TryGetValue(actionId, out var definition);
            var declaredPatches = definition?.Patches
                .Where(patch => patch.TargetId.Equals("state", StringComparison.Ordinal)
                                || componentIds.Contains(patch.TargetId))
                .Take(24)
                .ToArray() ?? [];

            _localActions.RegisterOrReplace(actionId, (evt, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                var now = DateTimeOffset.UtcNow;
                var patches = new List<GenUiStatePatch>();

                foreach (var declared in declaredPatches)
                {
                    patches.Add(new GenUiStatePatch(
                        Guid.NewGuid(), instanceId, GenUiPatchOperation.Replace,
                        declared.TargetId, declared.Path, declared.Value.Clone(), now));
                }

                if (evt.Value is { ValueKind: not JsonValueKind.Null and not JsonValueKind.Undefined })
                {
                    patches.Add(new GenUiStatePatch(
                        Guid.NewGuid(), instanceId, GenUiPatchOperation.Replace,
                        evt.ComponentId, "value", evt.Value, now));
                }

                if (evt.StructuredPayload.TryGetProperty("values", out var values) && values.ValueKind == JsonValueKind.Object)
                {
                    foreach (var val in values.EnumerateObject().Take(32))
                    {
                        if (!GenerativeUiContractValidator.ValidatePropertyName(val.Name)) continue;
                        patches.Add(new GenUiStatePatch(
                            Guid.NewGuid(), instanceId, GenUiPatchOperation.Replace,
                            "state", val.Name, val.Value.Clone(), now));
                    }
                }

                if (!declaredPatches.Any(patch => patch.TargetId.Equals(statusId, StringComparison.Ordinal)
                                                  && patch.Path.Equals("text", StringComparison.Ordinal)))
                {
                    var feedback = string.IsNullOrWhiteSpace(definition?.Message)
                        ? $"Action '{actionId}' completed"
                        : definition!.Message!;
                    patches.Add(new GenUiStatePatch(
                        Guid.NewGuid(), instanceId, GenUiPatchOperation.Replace,
                        statusId, "text", JsonSerializer.SerializeToElement(feedback), now));
                }

                return Task.FromResult(GenerativeUiEventRouter.Result(
                    evt, GenUiActionStatus.Completed,
                    string.IsNullOrWhiteSpace(definition?.Message)
                        ? $"Action '{actionId}' processed."
                        : definition!.Message!,
                    JsonSerializer.SerializeToElement(new { action = actionId, componentId = evt.ComponentId }),
                    patches));
            });
        }
    }

    private static string? FindStatusComponentId(GenUiComponent component)
    {
        if (component.ComponentType == "HavenStatus") return component.ComponentId;
        foreach (var child in component.Children)
        {
            var found = FindStatusComponentId(child);
            if (found is not null) return found;
        }
        return null;
    }

    private static HashSet<string> CollectActionIds(GenUiComponent component)
    {
        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var action in component.Actions)
            ids.Add(action.ActionId);
        foreach (var child in component.Children)
            ids.UnionWith(CollectActionIds(child));
        return ids;
    }

    private static HashSet<string> CollectComponentIds(GenUiComponent component)
    {
        var ids = new HashSet<string>(StringComparer.Ordinal) { component.ComponentId };
        foreach (var child in component.Children)
            ids.UnionWith(CollectComponentIds(child));
        return ids;
    }

    private static GenUiComponent BuildComponentTree(
        JsonElement componentsEl,
        Dictionary<string, CustomActionDefinition> actionDefinitions)
    {
        var children = componentsEl.EnumerateArray()
            .Where(el => el.ValueKind == JsonValueKind.Object)
            .Select(el => BuildComponent(el, actionDefinitions))
            .ToArray();

        if (children.Length > 1)
            return new GenUiComponent("custom.workspace", "HavenStack",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["spacing"] = JsonSerializer.SerializeToElement(10),
                    ["horizontalAlignment"] = JsonSerializer.SerializeToElement("stretch")
                }, [], children);

        return children.Length == 1 ? children[0] :
            new GenUiComponent("custom.empty", "HavenText",
                new Dictionary<string, JsonElement>(StringComparer.Ordinal)
                {
                    ["text"] = JsonSerializer.SerializeToElement("Empty")
                }, [], []);
    }

    private static GenUiComponent BuildComponent(
        JsonElement el,
        Dictionary<string, CustomActionDefinition> actionDefinitions)
    {
        var id = el.TryGetProperty("id", out var idEl) && idEl.ValueKind == JsonValueKind.String
            ? idEl.GetString() ?? Guid.NewGuid().ToString("N")[..8]
            : Guid.NewGuid().ToString("N")[..8];

        var type = el.TryGetProperty("type", out var typeEl) && typeEl.ValueKind == JsonValueKind.String
            ? typeEl.GetString() ?? "HavenText" : "HavenText";

        if (!GenerativeUiContractValidator.TrustedComponentTypes.Contains(type))
            type = "HavenText";

        var props = new Dictionary<string, JsonElement>(StringComparer.Ordinal);
        if (el.TryGetProperty("props", out var propsEl) && propsEl.ValueKind == JsonValueKind.Object)
        {
            foreach (var prop in propsEl.EnumerateObject())
            {
                if (!GenerativeUiContractValidator.ValidatePropertyName(prop.Name)) continue;
                props[prop.Name] = prop.Value.Clone();
            }
        }

        var actions = new List<GenUiActionBinding>();
        if (el.TryGetProperty("actions", out var actionsEl) && actionsEl.ValueKind == JsonValueKind.Array)
        {
            foreach (var action in actionsEl.EnumerateArray().Take(12))
            {
                if (action.ValueKind != JsonValueKind.Object) continue;
                var actionId = action.TryGetProperty("id", out var aid) && aid.ValueKind == JsonValueKind.String
                    ? aid.GetString()?.Trim() ?? string.Empty : string.Empty;
                if (string.IsNullOrWhiteSpace(actionId) || actionId.Length > 120) continue;

                actions.Add(new GenUiActionBinding(
                    actionId,
                    GenUiRouteKind.Local,
                    actionId,
                    CapabilityRiskClass.Low,
                    false));

                if (!actionDefinitions.ContainsKey(actionId))
                    actionDefinitions[actionId] = ParseActionDefinition(actionId, action);
            }
        }

        var children = new List<GenUiComponent>();
        if (el.TryGetProperty("children", out var childrenEl) && childrenEl.ValueKind == JsonValueKind.Array)
        {
            foreach (var child in childrenEl.EnumerateArray())
            {
                if (child.ValueKind == JsonValueKind.Object)
                    children.Add(BuildComponent(child, actionDefinitions));
            }
        }

        return new GenUiComponent(id, type, props, actions, children);
    }

    private static CustomActionDefinition ParseActionDefinition(string actionId, JsonElement action)
    {
        var message = action.TryGetProperty("message", out var messageElement)
                      && messageElement.ValueKind == JsonValueKind.String
            ? messageElement.GetString()?.Trim()
            : null;
        if (message?.Length > 240) message = message[..240];

        var patches = new List<CustomActionPatch>();
        if (action.TryGetProperty("patches", out var patchesElement)
            && patchesElement.ValueKind == JsonValueKind.Array)
        {
            foreach (var patch in patchesElement.EnumerateArray().Take(24))
            {
                if (patch.ValueKind != JsonValueKind.Object) continue;
                if (!patch.TryGetProperty("target", out var targetElement)
                    || targetElement.ValueKind != JsonValueKind.String)
                    continue;
                if (!patch.TryGetProperty("path", out var pathElement)
                    || pathElement.ValueKind != JsonValueKind.String)
                    continue;
                if (!patch.TryGetProperty("value", out var valueElement)) continue;

                var target = targetElement.GetString()?.Trim() ?? string.Empty;
                var path = pathElement.GetString()?.Trim() ?? string.Empty;
                if (target.Length is < 1 or > 120 || !IsSafePatchPath(path))
                    continue;
                if (valueElement.GetRawText().Length > 1024) continue;

                patches.Add(new CustomActionPatch(target, path, valueElement.Clone()));
            }
        }

        return new CustomActionDefinition(actionId, message, patches);
    }

    private static bool IsSafePatchPath(string path) =>
        path.Length is >= 1 and <= 120
        && GenerativeUiContractValidator.ValidatePropertyName(path)
        && path.All(character => char.IsLetterOrDigit(character) || character is '_' or '-' or '.');

    private sealed record CustomActionDefinition(
        string ActionId,
        string? Message,
        IReadOnlyList<CustomActionPatch> Patches);

    private sealed record CustomActionPatch(string TargetId, string Path, JsonElement Value);
}
