using System.Globalization;
using System.Text.Json;
using Avalonia.Controls;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using Haven.Application;
using Haven.Core;
using Haven.Desktop.HavenUI.Backend;
using Haven.UI;
using Haven.UI.Components;
using HavenButton = Haven.UI.Components.Button;
using HavenContainer = Haven.UI.Components.Container;
using HavenPage = Haven.UI.Components.Page;
using HavenText = Haven.UI.Components.Text;

namespace Haven.Desktop.Views.Pages.Imagine;

/// <summary>Avalonia is only the platform host/file-picker boundary; all visible Imagine product UI is Haven.UI.</summary>
public sealed class ImaginePage : UserControl, IDisposable
{
    private readonly IImagineProjectRepository _projects; private readonly IImagineSemanticService _semantic; private readonly IImagineAssistantService _assistant;
    private readonly ImagineScene _scene; private readonly HavenSceneControl _host; private ImagineProjectSession? _session; private IReadOnlyList<ImagineProject> _recent = [];
    private CancellationTokenSource? _operationCancellation; private CancellationTokenSource? _autosaveCancellation; private bool _initialised; private bool _disposed;
    public ImaginePage(IImagineProjectRepository projects, IImagineSemanticService semantic, IImagineAssistantService assistant)
    {
        _projects = projects; _semantic = semantic; _assistant = assistant; _scene = new ImagineScene(); _host = new HavenSceneControl { Root = _scene.Root }; Content = _host;
        _host.InputSubmitted += input => { if (ReferenceEquals(input, _scene.AssistantInput)) _ = ApplyAssistantAsync(_scene.AssistantInput.Text); else if (ReferenceEquals(input, _scene.TextInput)) AddText(); };
        WireScene(); AttachedToVisualTree += (_, _) => _ = InitialiseAsync(); SizeChanged += (_, e) => _scene.SetViewportWidth(e.NewSize.Width);
    }
    public Guid? ProjectId => _session?.Project.Id; public event Action<string>? InspectInVisionRequested;
    public async Task ImportPathAsync(string path)
    {
        if (_session is null || string.IsNullOrWhiteSpace(path)) return; var kind = MediaKind(path); if (kind is null) { SetStatus("Imagine supports common image, audio and video files."); return; }
        await RunOperationAsync("Importing media…", async token => { var asset = await _projects.ImportAssetAsync(_session.Project.Id, path, kind.Value, token); _session.AddImportedAsset(asset); await _projects.SaveAsync(_session.Project, token); SetStatus($"Imported {asset.Name}. The source file was left unchanged."); });
    }
    private void WireScene()
    {
        _scene.ImportRequested += async (_, _) => await PickImportAsync(); _scene.SaveRequested += async (_, _) => await SaveAsync(); _scene.ExportRequested += async (_, _) => await ExportAsync();
        _scene.UndoRequested += (_, _) => { if (_session?.Undo() == true) SetStatus("Undo"); }; _scene.RedoRequested += (_, _) => { if (_session?.Redo() == true) SetStatus("Redo"); };
        _scene.AddRectangleRequested += (_, _) => { _session?.AddRectangle(); SetStatus("Rectangle added."); }; _scene.AddTextRequested += (_, _) => AddText(); _scene.DuplicateRequested += (_, _) => { if (_session?.DuplicateSelected() == true) SetStatus("Selection duplicated."); }; _scene.DeleteRequested += (_, _) => { if (_session?.DeleteSelected() == true) SetStatus("Selection deleted."); };
        _scene.DecomposeRequested += async (_, _) => await DecomposeAsync(); _scene.FitRequested += (_, _) => _scene.Canvas.Fit(); _scene.ProjectRequested += project => _ = OpenProjectAsync(project.Id); _scene.AssetRequested += SelectAsset; _scene.ComponentRequested += component => _session?.SelectSemanticComponent(component.Id); _scene.AssistantRequested += prompt => _ = ApplyAssistantAsync(prompt); _scene.InspectVisionRequested += (_, _) => InspectSelectedInVision();
    }
    private async Task InitialiseAsync()
    {
        if (_initialised || _disposed) return; _initialised = true; SetStatus("Loading Imagine projects…");
        try { _recent = await _projects.GetRecentAsync(20, CancellationToken.None); var project = _recent.FirstOrDefault() ?? await _projects.CreateAsync("Untitled Imagine Project", 1600, 1000, CancellationToken.None); AttachSession(new ImagineProjectSession(project)); await RefreshRecentAsync(CancellationToken.None); SetStatus("Ready. Import an image to begin editing, or add text and shapes."); }
        catch (Exception exception) when (exception is IOException or InvalidOperationException or JsonException) { SetStatus("Imagine could not load its project workspace: " + exception.Message); }
    }
    private async Task OpenProjectAsync(Guid id) => await RunOperationAsync("Opening project…", async token => { var project = await _projects.GetAsync(id, token); if (project is null) { SetStatus("That Imagine project no longer exists."); return; } AttachSession(new ImagineProjectSession(project)); SetStatus($"Opened {project.Name}."); });
    private void AttachSession(ImagineProjectSession session) { if (_session is not null) _session.Changed -= OnSessionChanged; _session = session; _session.Changed += OnSessionChanged; _scene.SetSession(session); RefreshScene(); }
    private void OnSessionChanged(object? sender, EventArgs e) { Dispatcher.UIThread.Post(RefreshScene); QueueAutosave(); }
    private void QueueAutosave() { _autosaveCancellation?.Cancel(); _autosaveCancellation?.Dispose(); var cancellation = new CancellationTokenSource(); _autosaveCancellation = cancellation; _ = AutosaveAsync(cancellation); }
    private async Task AutosaveAsync(CancellationTokenSource cancellation) { try { await Task.Delay(180, cancellation.Token); if (_session is { } session) await _projects.SaveAsync(session.Project, cancellation.Token); } catch (OperationCanceledException) when (cancellation.IsCancellationRequested) { } catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or InvalidOperationException) { await Dispatcher.UIThread.InvokeAsync(() => SetStatus("Autosave failed: " + exception.Message)); } }
    private async Task PickImportAsync() { var storage = TopLevel.GetTopLevel(this)?.StorageProvider; if (storage is null) { SetStatus("The platform file picker is unavailable."); return; } var files = await storage.OpenFilePickerAsync(new FilePickerOpenOptions { Title = "Import media into Imagine", AllowMultiple = true }); foreach (var path in files.Select(file => file.TryGetLocalPath()).OfType<string>()) await ImportPathAsync(path); }
    private async Task SaveAsync() { if (_session is null) return; await RunOperationAsync("Saving project…", async token => { await _projects.SaveAsync(_session.Project, token); await RefreshRecentAsync(token); SetStatus("Project saved."); }); }
    private async Task ExportAsync()
    {
        if (_session is null) return; var storage = TopLevel.GetTopLevel(this)?.StorageProvider; if (storage is null) { SetStatus("The platform save picker is unavailable."); return; } var destination = await storage.SaveFilePickerAsync(new FilePickerSaveOptions { Title = "Export Imagine project bundle", SuggestedFileName = SafeFileName(_session.Project.Name) + ".haven-imagine" }); var path = destination?.TryGetLocalPath(); if (string.IsNullOrWhiteSpace(path)) return;
        await RunOperationAsync("Exporting project…", async token => { await _projects.SaveAsync(_session.Project, token); var exported = await _projects.ExportBundleAsync(_session.Project, path, token); SetStatus("Exported project bundle to " + exported); });
    }
    private async Task DecomposeAsync() { if (_session is null) return; var assetId = SelectedImageAssetId(); if (assetId is null) { SetStatus("Select an imported image object before semantic decomposition."); return; } await RunOperationAsync("Analysing semantic components…", async token => { var result = await _semantic.DecomposeImageAsync(_session.Project, assetId.Value, token); if (result.Succeeded) { _session.ReplaceSemanticComponents(assetId.Value, result.Components, result.Model); await _projects.SaveAsync(_session.Project, token); } SetStatus(result.Status); }); }
    private async Task ApplyAssistantAsync(string instruction)
    {
        if (_session is null || string.IsNullOrWhiteSpace(instruction)) return; ImagineAiEditRequest request; try { request = _session.CreateAiEditRequest(instruction); } catch (Exception exception) when (exception is ArgumentException or InvalidOperationException) { SetStatus(exception.Message); return; } _scene.AssistantInput.Text = string.Empty;
        await RunOperationAsync("Haven is editing the selected object…", async token => { var result = await _assistant.ProposeEditAsync(_session.Project, request, token); if (result.Succeeded && _session.ApplyAssistantObjectEdit(result)) await _projects.SaveAsync(_session.Project, token); SetStatus(result.Status); });
    }
    private void AddText() { if (_session is null) return; var value = _scene.TextInput.Text.Trim(); _session.AddText(string.IsNullOrWhiteSpace(value) ? "Text" : value); _scene.TextInput.Text = string.Empty; SetStatus("Text added."); }
    private void SelectAsset(ImagineMediaAsset asset) { if (_session is null) return; var match = _session.Project.Objects.LastOrDefault(item => item.AssetId == asset.Id); if (match is not null) _session.SelectObject(match.Id); else SetStatus($"{asset.Name} is in the shared media project model. Timeline editing controls are not exposed until their real media services are installed."); }
    private void InspectSelectedInVision() { if (_session is null) return; var assetId = SelectedImageAssetId(); var path = assetId is Guid id ? _session.Project.Assets.FirstOrDefault(item => item.Id == id)?.ManagedPath : null; if (string.IsNullOrWhiteSpace(path)) { SetStatus("Select an image before opening it in Vision."); return; } InspectInVisionRequested?.Invoke(path); }
    private Guid? SelectedImageAssetId() { if (_session is null) return null; var selection = _session.Project.Selection; if (selection.Kind == ImagineSelectionKind.Object && selection.TargetId is Guid objectId && _session.Project.Objects.FirstOrDefault(item => item.Id == objectId)?.AssetId is Guid assetId && _session.Project.Assets.Any(item => item.Id == assetId && item.Kind == ImagineMediaKind.Image)) return assetId; if (selection.Kind == ImagineSelectionKind.SemanticComponent && selection.TargetId is Guid componentId) return _session.Project.SemanticComponents.FirstOrDefault(item => item.Id == componentId)?.AssetId; return null; }
    private async Task RefreshRecentAsync(CancellationToken token) { _recent = await _projects.GetRecentAsync(20, token); await Dispatcher.UIThread.InvokeAsync(RefreshScene); } private void RefreshScene() { if (_session is null) { _scene.SetUnavailable("No Imagine project is open."); return; } _scene.Sync(_session.Project, _recent); }
    private async Task RunOperationAsync(string status, Func<CancellationToken, Task> operation) { _operationCancellation?.Cancel(); _operationCancellation?.Dispose(); var cancellation = new CancellationTokenSource(TimeSpan.FromSeconds(60)); _operationCancellation = cancellation; SetStatus(status); try { await operation(cancellation.Token); } catch (OperationCanceledException) when (cancellation.IsCancellationRequested) { SetStatus("Operation cancelled or timed out. The project was left in its last committed state."); } catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or InvalidOperationException or JsonException or HttpRequestException) { SetStatus("Imagine operation failed: " + exception.Message); } finally { if (ReferenceEquals(_operationCancellation, cancellation)) _operationCancellation = null; cancellation.Dispose(); } }
    private void SetStatus(string value) => Dispatcher.UIThread.Post(() => _scene.SetStatus(value));
    private static ImagineMediaKind? MediaKind(string path) => Path.GetExtension(path).ToLowerInvariant() switch { ".png" or ".jpg" or ".jpeg" or ".webp" or ".gif" or ".bmp" => ImagineMediaKind.Image, ".wav" or ".mp3" or ".m4a" or ".aac" or ".flac" or ".ogg" => ImagineMediaKind.Audio, ".mp4" or ".mov" or ".mkv" or ".webm" or ".avi" => ImagineMediaKind.Video, _ => null };
    private static string SafeFileName(string value) { var invalid = Path.GetInvalidFileNameChars().ToHashSet(); var safe = new string(value.Select(c => invalid.Contains(c) ? '_' : c).ToArray()).Trim(); return string.IsNullOrWhiteSpace(safe) ? "Imagine Project" : safe; }
    public void Dispose() { if (_disposed) return; _disposed = true; if (_session is not null) _session.Changed -= OnSessionChanged; _operationCancellation?.Cancel(); _operationCancellation?.Dispose(); _autosaveCancellation?.Cancel(); _autosaveCancellation?.Dispose(); _scene.Dispose(); }
}

internal sealed class ImagineScene : IDisposable
{
    private readonly HavenPrefabCatalog _prefabs; private readonly DynamicUI _dynamic; private string _signature = string.Empty;
    public ImagineScene()
    {
        _prefabs = HavenPrefabCatalog.FromAssembly(typeof(ImagineScene).Assembly); Root = new HavenPage { Name = "Imagine.Root", Layout = HavenLayout.Vertical }; Root.SetValue(HavenProperties.Width, HavenLength.Percent(100)); Root.SetValue(HavenProperties.Height, HavenLength.Percent(100)); Root.SetValue(HavenProperties.Gap, HavenLength.Px(10)); Root.SetValue(HavenProperties.Padding, HavenThickness.Parse("14px 16px")); Root.Accessibility.AccessibleName = "Imagine creative editor";
        var toolbar = Wrap("Imagine.Toolbar", 6); foreach (var button in new[] { Action("Import", "Import", "plus"), Action("Save", "Save", "file"), Action("Export", "Export", "archive"), Action("Undo", "Undo", "chevron-left"), Action("Redo", "Redo", "chevron-right"), Action("AddRectangle", "Rectangle", "window"), Action("Duplicate", "Duplicate", "plus"), Action("Delete", "Delete", "delete"), Action("Decompose", "Semantic parts", "sparkles"), Action("Fit", "Fit canvas", "search"), Action("InspectVision", "Inspect in Vision", "vision") }) toolbar.Add(button); TextInput = new Input { Name = "Imagine.TextInput", Placeholder = "Text to add", SubmitOnEnter = true }; TextInput.SetValue(HavenProperties.MinWidth, HavenLength.Px(160)); toolbar.Add(TextInput); toolbar.Add(Action("AddText", "Add text", "edit")); Root.Add(toolbar);
        Body = Grid("Imagine.Body", "240px 1fr 300px", "1fr"); Body.SetValue(HavenProperties.MinHeight, HavenLength.Px(520)); Root.Add(Body);
        var left = Vertical("Imagine.Left", 8); left.SetValue(HavenProperties.Column, 0); left.SetValue(HavenProperties.Overflow, HavenOverflow.Scroll); Body.Add(left); left.Add(Heading("Projects")); RecentProjects = Runtime("Imagine.RecentProjects"); left.Add(RecentProjects); left.Add(Heading("Media")); Assets = Runtime("Imagine.Assets"); left.Add(Assets); TrackSummary = Muted("Imagine.TrackSummary", "No audio/video tracks."); left.Add(TrackSummary);
        Canvas = new ImagineCanvasElement { Name = "Imagine.Canvas" }; Canvas.SetValue(HavenProperties.Column, 1); Canvas.SetValue(HavenProperties.Width, HavenLength.Percent(100)); Canvas.SetValue(HavenProperties.Height, HavenLength.Percent(100)); Canvas.SetValue(HavenProperties.MinHeight, HavenLength.Px(500)); Body.Add(Canvas);
        var right = Vertical("Imagine.Right", 8); right.SetValue(HavenProperties.Column, 2); right.SetValue(HavenProperties.Overflow, HavenOverflow.Scroll); Body.Add(right); ProjectTitle = Heading("Untitled Imagine Project"); right.Add(ProjectTitle); Selection = Muted("Imagine.Selection", "Nothing selected."); right.Add(Selection); right.Add(Heading("Semantic components")); Components = Runtime("Imagine.Components"); right.Add(Components); ComponentsEmpty = Muted("Imagine.ComponentsEmpty", "No semantic decomposition yet. Select an image and choose Semantic parts."); right.Add(ComponentsEmpty); Status = Muted("Imagine.Status", "Loading…"); right.Add(Status);
        Assistant = _prefabs.Create("Chatbox", "Imagine-Chatbox"); AssistantInput = Assistant.GetComponent<Input>("Instruction"); AssistantInput.Placeholder = "Ask Haven to edit the selected object"; AssistantInput.Multiline = true; AssistantInput.SubmitOnEnter = true; Assistant.GetComponent<HavenButton>("AddMenu").SetValue(HavenProperties.Visibility, HavenVisibility.Collapsed); AssistantSend = Assistant.GetComponent<HavenButton>("Send"); AssistantSend.Accessibility.AccessibleName = "Apply AI structural edit to selection"; Root.Add(Assistant);
        _dynamic = new DynamicUI(Root, HavenDynamicUITemplateCatalog.FromAssembly(typeof(ImagineScene).Assembly), _prefabs); Wire("Import", () => ImportRequested?.Invoke(this, EventArgs.Empty)); Wire("Save", () => SaveRequested?.Invoke(this, EventArgs.Empty)); Wire("Export", () => ExportRequested?.Invoke(this, EventArgs.Empty)); Wire("Undo", () => UndoRequested?.Invoke(this, EventArgs.Empty)); Wire("Redo", () => RedoRequested?.Invoke(this, EventArgs.Empty)); Wire("AddRectangle", () => AddRectangleRequested?.Invoke(this, EventArgs.Empty)); Wire("AddText", () => AddTextRequested?.Invoke(this, EventArgs.Empty)); Wire("Duplicate", () => DuplicateRequested?.Invoke(this, EventArgs.Empty)); Wire("Delete", () => DeleteRequested?.Invoke(this, EventArgs.Empty)); Wire("Decompose", () => DecomposeRequested?.Invoke(this, EventArgs.Empty)); Wire("Fit", () => FitRequested?.Invoke(this, EventArgs.Empty)); Wire("InspectVision", () => InspectVisionRequested?.Invoke(this, EventArgs.Empty)); AssistantSend.Invoked += (_, _) => SubmitAssistant(); SetViewportWidth(1280);
    }
    public HavenPage Root { get; } public HavenContainer Body { get; } public DynamicUIRuntime RecentProjects { get; } public DynamicUIRuntime Assets { get; } public DynamicUIRuntime Components { get; } public ImagineCanvasElement Canvas { get; } public HavenText ProjectTitle { get; } public HavenText Selection { get; } public HavenText TrackSummary { get; } public HavenText ComponentsEmpty { get; } public HavenText Status { get; } public Prefab Assistant { get; } public Input AssistantInput { get; } public HavenButton AssistantSend { get; } public Input TextInput { get; }
    public event EventHandler? ImportRequested; public event EventHandler? SaveRequested; public event EventHandler? ExportRequested; public event EventHandler? UndoRequested; public event EventHandler? RedoRequested; public event EventHandler? AddRectangleRequested; public event EventHandler? AddTextRequested; public event EventHandler? DuplicateRequested; public event EventHandler? DeleteRequested; public event EventHandler? DecomposeRequested; public event EventHandler? FitRequested; public event EventHandler? InspectVisionRequested; public event Action<ImagineProject>? ProjectRequested; public event Action<ImagineMediaAsset>? AssetRequested; public event Action<ImagineSemanticComponent>? ComponentRequested; public event Action<string>? AssistantRequested;
    public void SetSession(ImagineProjectSession session) { Canvas.SetSession(session); _signature = string.Empty; }
    public void Sync(ImagineProject project, IReadOnlyList<ImagineProject> recent)
    {
        ProjectTitle.Content = project.Name; Selection.Content = SelectionLabel(project); TrackSummary.Content = project.Tracks.Length == 0 ? "No audio/video tracks." : string.Join(" · ", project.Tracks.GroupBy(track => track.Kind).Select(group => $"{group.Count()} {group.Key.ToString().ToLowerInvariant()} track{(group.Count() == 1 ? string.Empty : "s")}")); Canvas.InvalidateCanvas(); var signature = project.UpdatedAt.UtcDateTime.Ticks + "|" + string.Join('|', recent.Select(item => item.Id + ":" + item.UpdatedAt.UtcDateTime.Ticks)); if (signature == _signature) return; _signature = signature; RecentProjects.ClearItems(); Assets.ClearItems(); Components.ClearItems();
        foreach (var item in recent.Take(20)) { var row = _dynamic.CreateItem("ImagineProjectRow", RecentProjects.Name!, "project-" + item.Id.ToString("N"), new Dictionary<string, object?> { ["TITLE"] = item.Name, ["DETAIL"] = item.UpdatedAt.LocalDateTime.ToString("d MMM HH:mm") }); row.GetComponent<HavenButton>("Open").Invoked += (_, _) => ProjectRequested?.Invoke(item); }
        foreach (var asset in project.Assets.OrderByDescending(item => item.CreatedAt)) { var row = _dynamic.CreateItem("ImagineAssetRow", Assets.Name!, "asset-" + asset.Id.ToString("N"), new Dictionary<string, object?> { ["TITLE"] = asset.Name, ["DETAIL"] = asset.Kind + " · " + FormatBytes(asset.SizeBytes) }); row.GetComponent<HavenButton>("Open").Invoked += (_, _) => AssetRequested?.Invoke(asset); }
        foreach (var component in project.SemanticComponents.OrderBy(item => item.Order)) { var depth = Depth(component, project.SemanticComponents); var row = _dynamic.CreateItem("ImagineComponentRow", Components.Name!, "component-" + component.Id.ToString("N"), new Dictionary<string, object?> { ["TITLE"] = new string('·', depth) + (depth == 0 ? string.Empty : " ") + component.Label, ["DETAIL"] = component.Confidence is double confidence ? $"{component.Type} · {confidence:P0}" : component.Type }); row.GetComponent<HavenButton>("Open").Invoked += (_, _) => ComponentRequested?.Invoke(component); } ComponentsEmpty.SetValue(HavenProperties.Visibility, project.SemanticComponents.Length == 0 ? HavenVisibility.Visible : HavenVisibility.Collapsed);
    }
    public void SetStatus(string value) => Status.Content = value; public void SetUnavailable(string value) { Status.Content = value; RecentProjects.ClearItems(); Assets.ClearItems(); Components.ClearItems(); }
    public void SetViewportWidth(double width) { if (!double.IsFinite(width) || width <= 0) return; Body.Columns = width < 760 ? "1fr" : width < 1100 ? "220px 1fr" : "240px 1fr 300px"; foreach (var child in Body.Children) child.SetValue(HavenProperties.Visibility, HavenVisibility.Visible); if (width < 760) { Body.Children[0].SetValue(HavenProperties.Visibility, HavenVisibility.Collapsed); Body.Children[2].SetValue(HavenProperties.Visibility, HavenVisibility.Collapsed); Canvas.SetValue(HavenProperties.Column, 0); } else if (width < 1100) { Body.Children[2].SetValue(HavenProperties.Visibility, HavenVisibility.Collapsed); Canvas.SetValue(HavenProperties.Column, 1); } else Canvas.SetValue(HavenProperties.Column, 1); }
    private void SubmitAssistant() { var prompt = AssistantInput.Text.Trim(); if (!string.IsNullOrWhiteSpace(prompt)) AssistantRequested?.Invoke(prompt); }
    private static string SelectionLabel(ImagineProject project) { var selection = project.Selection; if (selection.Kind == ImagineSelectionKind.Object && selection.TargetId is Guid objectId && project.Objects.FirstOrDefault(item => item.Id == objectId) is { } obj) return $"Selected: {obj.Name} · x {obj.Transform.X:0} y {obj.Transform.Y:0} · {obj.Transform.Width:0}×{obj.Transform.Height:0} · {obj.Transform.RotationDegrees:0.#}°"; if (selection.Kind == ImagineSelectionKind.SemanticComponent && selection.TargetId is Guid componentId && project.SemanticComponents.FirstOrDefault(item => item.Id == componentId) is { } component) return $"Semantic selection: {component.Label} · {component.Type}"; if (selection.Kind == ImagineSelectionKind.Track) return "Audio/video track selected."; return "Nothing selected."; }
    private static int Depth(ImagineSemanticComponent component, IReadOnlyList<ImagineSemanticComponent> all) { var depth = 0; var parent = component.ParentId; var guard = 0; while (parent is Guid id && guard++ < 12) { depth++; parent = all.FirstOrDefault(item => item.Id == id)?.ParentId; } return depth; } private static string FormatBytes(long bytes) => bytes >= 1048576 ? $"{bytes / 1048576d:0.#} MB" : bytes >= 1024 ? $"{bytes / 1024d:0.#} KB" : $"{bytes} B"; private T Find<T>(string name) where T : HavenElement => Root.DescendantsAndSelf().OfType<T>().Single(item => item.Name == name); private void Wire(string name, Action action) => Find<HavenButton>(name).Invoked += (_, _) => action();
    private static HavenButton Action(string name, string content, string icon) => new() { Name = name, Content = content, IconKey = icon, Variant = ButtonVariant.Ghost }; private static HavenContainer Grid(string name, string columns, string rows) { var value = new HavenContainer { Name = name, Layout = HavenLayout.Grid, Columns = columns, Rows = rows }; value.SetValue(HavenProperties.Width, HavenLength.Percent(100)); value.SetValue(HavenProperties.Gap, HavenLength.Px(10)); return value; } private static HavenContainer Vertical(string name, double gap) { var value = new HavenContainer { Name = name, Layout = HavenLayout.Vertical }; value.SetValue(HavenProperties.Width, HavenLength.Percent(100)); value.SetValue(HavenProperties.Gap, HavenLength.Px(gap)); return value; } private static HavenContainer Wrap(string name, double gap) { var value = new HavenContainer { Name = name, Layout = HavenLayout.Wrap }; value.SetValue(HavenProperties.Width, HavenLength.Percent(100)); value.SetValue(HavenProperties.Gap, HavenLength.Px(gap)); return value; } private static DynamicUIRuntime Runtime(string name) { var value = new DynamicUIRuntime { Name = name }; value.SetValue(HavenProperties.Width, HavenLength.Percent(100)); return value; } private static HavenText Heading(string content) { var value = new HavenText { Content = content, Level = TextLevel.H3 }; value.SetValue(HavenProperties.FontWeight, 750); return value; } private static HavenText Muted(string name, string content) { var value = new HavenText { Name = name, Content = content }; value.SetValue(HavenProperties.Foreground, "TextSecondary"); value.SetValue(HavenProperties.FontSize, 11d); return value; } public void Dispose() { RecentProjects.ClearItems(); Assets.ClearItems(); Components.ClearItems(); Canvas.Dispose(); }
}

internal sealed class ImagineCanvasElement : HavenElement, IHavenDrawCommandSource, IHavenPointerInputTarget, IHavenScrollInputTarget, IDisposable
{
    private enum Interaction { None, Move, Resize, Rotate, Pan } private ImagineProjectSession? _session; private Interaction _interaction; private ImagineEditableObject? _original; private ImagineTransform? _preview; private HavenPoint _pointerStart; private HavenPoint _offset; private double _zoom = 1; private bool _fitPending = true;
    public ImagineCanvasElement() { Accessibility.Role = HavenAccessibleRole.Image; Accessibility.Focusable = true; Accessibility.AccessibleName = "Imagine editable canvas"; SetValue(HavenProperties.Background, "SurfaceRaised"); SetValue(HavenProperties.BorderColor, "Border"); SetValue(HavenProperties.BorderWidth, HavenLength.Px(1)); SetValue(HavenProperties.Radius, HavenCornerRadius.Uniform(HavenLength.Px(16))); SetValue(HavenProperties.Clip, true); } public void SetSession(ImagineProjectSession session) { if (ReferenceEquals(_session, session)) return; if (_session is not null) _session.Changed -= OnSessionChanged; _session = session; _session.Changed += OnSessionChanged; _fitPending = true; Invalidate(); } public void Fit() { _fitPending = true; Invalidate(); } public void InvalidateCanvas() => Invalidate();
    public bool PointerPressed(HavenPointerInput input) { if (_session is null) return false; EnsureFit(); _pointerStart = input.LocalPosition; var selected = SelectedObject(); if (selected is not null && HandleHit(selected.Transform, input.LocalPosition, true)) { _interaction = Interaction.Rotate; _original = selected; _preview = selected.Transform; return true; } if (selected is not null && HandleHit(selected.Transform, input.LocalPosition, false)) { _interaction = Interaction.Resize; _original = selected; _preview = selected.Transform; return true; } var board = ToBoard(input.LocalPosition); var hit = _session.Project.Objects.Where(item => item.IsVisible).OrderByDescending(item => item.ZIndex).FirstOrDefault(item => Contains(item.Transform, board)); if (hit is not null) { _session.SelectObject(hit.Id); _interaction = Interaction.Move; _original = hit; _preview = hit.Transform; return true; } _session.ClearSelection(); _interaction = Interaction.Pan; return true; }
    public bool PointerMoved(HavenPointerInput input) { if (_session is null) return false; var delta = new HavenPoint((input.LocalPosition.X - _pointerStart.X) / Math.Max(.05, _zoom), (input.LocalPosition.Y - _pointerStart.Y) / Math.Max(.05, _zoom)); if (_original is not null && _preview is not null) _preview = _interaction switch { Interaction.Move => _original.Transform with { X = _original.Transform.X + delta.X, Y = _original.Transform.Y + delta.Y }, Interaction.Resize => _original.Transform with { Width = Math.Max(12, _original.Transform.Width + delta.X), Height = Math.Max(12, _original.Transform.Height + delta.Y) }, Interaction.Rotate => _original.Transform with { RotationDegrees = RotationFor(_original.Transform, input.LocalPosition) }, _ => _preview }; else if (_interaction == Interaction.Pan) { _offset = new HavenPoint(_offset.X + input.LocalPosition.X - _pointerStart.X, _offset.Y + input.LocalPosition.Y - _pointerStart.Y); _pointerStart = input.LocalPosition; } Invalidate(); return true; }
    public bool PointerReleased(HavenPointerInput input) { if (_session is null) return false; if (_original is not null && _preview is not null && _interaction is Interaction.Move or Interaction.Resize or Interaction.Rotate) { var operation = _interaction == Interaction.Move ? "move" : _interaction == Interaction.Resize ? "resize" : "rotate"; _session.CommitObjectTransform(_original.Id, _preview, operation); } _interaction = Interaction.None; _original = null; _preview = null; Invalidate(); return true; }
    public bool PointerWheel(HavenPoint localPosition, double deltaX, double deltaY) { if (_session is null || Math.Abs(deltaY) < .001) return false; EnsureFit(); var before = ToBoard(localPosition); _zoom = Math.Clamp(_zoom * (deltaY < 0 ? 1.1 : .9), .05, 8); _offset = new HavenPoint(localPosition.X - before.X * _zoom, localPosition.Y - before.Y * _zoom); Invalidate(); return true; }
    public void Draw(HavenDrawingContext context, double opacity) { if (_session is null || Bounds.Width <= 2 || Bounds.Height <= 2) return; EnsureFit(); context.Add(new HavenFillRoundedRectCommand(Bounds, new HavenTokenBrush("SurfaceRaised"), 16, opacity)); var project = _session.Project; var canvas = ToScreen(new ImagineTransform(0, 0, project.CanvasWidth, project.CanvasHeight)); context.Add(new HavenFillRoundedRectCommand(canvas, new HavenSolidBrush(255, 255, 255, 255), 4, opacity)); context.Add(new HavenStrokeRoundedRectCommand(canvas, new HavenPen(new HavenTokenBrush("Border"), 1), 4, opacity)); foreach (var item in project.Objects.Where(item => item.IsVisible).OrderBy(item => item.ZIndex)) DrawObject(context, item, opacity); DrawSemanticBounds(context, opacity); if (SelectedObject() is { } selected) DrawSelection(context, selected, opacity); }
    private void DrawObject(HavenDrawingContext context, ImagineEditableObject item, double opacity) { var transform = _preview is not null && _original?.Id == item.Id ? _preview : item.Transform; var rect = ToScreen(transform); if (Math.Abs(transform.RotationDegrees) > .01) context.Add(new HavenPushTransformCommand(rect, new HavenTransform(RotationDegrees: transform.RotationDegrees), new HavenPoint(rect.X + rect.Width / 2, rect.Y + rect.Height / 2))); switch (item.Kind) { case ImagineObjectKind.Image: var source = item.AssetId is Guid assetId ? _session?.Project.Assets.FirstOrDefault(asset => asset.Id == assetId)?.ManagedPath : null; if (!string.IsNullOrWhiteSpace(source)) context.Add(new HavenImageCommand(rect, new HavenImage(source), HavenImageLayout.Contain, opacity)); break; case ImagineObjectKind.Ellipse: context.Add(new HavenEllipseCommand(rect, Brush(item.Fill), null, opacity)); break; case ImagineObjectKind.Text: context.Add(new HavenTextCommand(rect, new HavenTextLayout(item.Text, "Segoe UI", Math.Max(14, 26 * _zoom), 600, rect.Width, true), Brush(item.Fill), opacity)); break; default: context.Add(new HavenFillRoundedRectCommand(rect, Brush(item.Fill), 8, opacity)); break; } if (Math.Abs(transform.RotationDegrees) > .01) context.Add(new HavenPopTransformCommand(rect)); }
    private void DrawSemanticBounds(HavenDrawingContext context, double opacity) { if (_session is null) return; foreach (var component in _session.Project.SemanticComponents) { var image = _session.Project.Objects.LastOrDefault(item => item.AssetId == component.AssetId && item.Kind == ImagineObjectKind.Image); if (image is null) continue; var b = component.Bounds; var logical = new ImagineTransform(image.Transform.X + b.X * image.Transform.Width, image.Transform.Y + b.Y * image.Transform.Height, b.Width * image.Transform.Width, b.Height * image.Transform.Height); var screen = ToScreen(logical); var selected = _session.Project.Selection.Kind == ImagineSelectionKind.SemanticComponent && _session.Project.Selection.TargetId == component.Id; context.Add(new HavenStrokeRoundedRectCommand(screen, new HavenPen(new HavenSolidBrush((byte)(selected ? 255 : 150), 142, 36, 170), selected ? 2.5 : 1.2), 4, opacity)); } }
    private void DrawSelection(HavenDrawingContext context, ImagineEditableObject item, double opacity) { var transform = _preview is not null && _original?.Id == item.Id ? _preview : item.Transform; var rect = ToScreen(transform); var pen = new HavenPen(new HavenSolidBrush(255, 30, 136, 229), 2); context.Add(new HavenStrokeRoundedRectCommand(rect, pen, 5, opacity)); var resize = ResizeHandle(rect); context.Add(new HavenFillRoundedRectCommand(resize, new HavenSolidBrush(255, 30, 136, 229), 3, opacity)); var rotate = RotateHandle(rect); context.Add(new HavenLineCommand(new HavenPoint(rect.X + rect.Width / 2, rect.Y), new HavenPoint(rotate.X + rotate.Width / 2, rotate.Bottom), pen, opacity)); context.Add(new HavenEllipseCommand(rotate, new HavenSolidBrush(255, 255, 255, 255), pen, opacity)); }
    private ImagineEditableObject? SelectedObject() => _session?.Project.Selection is { Kind: ImagineSelectionKind.Object, TargetId: Guid id } ? _session.Project.Objects.FirstOrDefault(item => item.Id == id) : null; private void EnsureFit() { if (!_fitPending || _session is null || Bounds.Width <= 2 || Bounds.Height <= 2) return; var project = _session.Project; _zoom = Math.Clamp(Math.Min((Bounds.Width - 56) / project.CanvasWidth, (Bounds.Height - 56) / project.CanvasHeight), .05, 4); _offset = new HavenPoint((Bounds.Width - project.CanvasWidth * _zoom) / 2, (Bounds.Height - project.CanvasHeight * _zoom) / 2); _fitPending = false; } private HavenPoint ToBoard(HavenPoint local) => new((local.X - _offset.X) / Math.Max(.05, _zoom), (local.Y - _offset.Y) / Math.Max(.05, _zoom)); private HavenRect ToScreen(ImagineTransform value) => new(Bounds.X + _offset.X + value.X * _zoom, Bounds.Y + _offset.Y + value.Y * _zoom, value.Width * _zoom, value.Height * _zoom);
    private bool HandleHit(ImagineTransform transform, HavenPoint local, bool rotate) { var global = rotate ? RotateHandle(ToScreen(transform)) : ResizeHandle(ToScreen(transform)); var point = new HavenPoint(Bounds.X + local.X, Bounds.Y + local.Y); return point.X >= global.X - 5 && point.X <= global.Right + 5 && point.Y >= global.Y - 5 && point.Y <= global.Bottom + 5; } private static HavenRect ResizeHandle(HavenRect rect) => new(rect.Right - 6, rect.Bottom - 6, 12, 12); private static HavenRect RotateHandle(HavenRect rect) => new(rect.X + rect.Width / 2 - 7, rect.Y - 30, 14, 14); private static bool Contains(ImagineTransform value, HavenPoint point) => point.X >= value.X && point.X <= value.X + value.Width && point.Y >= value.Y && point.Y <= value.Y + value.Height; private double RotationFor(ImagineTransform value, HavenPoint local) { var center = new HavenPoint(_offset.X + (value.X + value.Width / 2) * _zoom, _offset.Y + (value.Y + value.Height / 2) * _zoom); return Math.Atan2(local.Y - center.Y, local.X - center.X) * 180 / Math.PI + 90; }
    private static HavenBrush Brush(string value) { if (value is not { Length: 7 } || value[0] != '#' || !value.Skip(1).All(Uri.IsHexDigit)) return new HavenSolidBrush(255, 17, 17, 17); return new HavenSolidBrush(255, byte.Parse(value.AsSpan(1, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture), byte.Parse(value.AsSpan(3, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture), byte.Parse(value.AsSpan(5, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture)); } private void OnSessionChanged(object? sender, EventArgs e) => Invalidate(); public void Dispose() { if (_session is not null) _session.Changed -= OnSessionChanged; }
}
