using Avalonia.Controls;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using Haven.Application;
using Haven.Core;
using Haven.Desktop.HavenUI.Backend;
using Haven.UI;
using Haven.UI.Components;
using HavenButton = Haven.UI.Components.Button;
using HavenContainer = Haven.UI.Components.Container;
using HavenPage = Haven.UI.Components.Page;
using HavenText = Haven.UI.Components.Text;

namespace Haven.Desktop.Views.Pages.Imagine;

/// <summary>Dedicated Haven-native visual understanding and OCR workspace.</summary>
public sealed class VisionPage : UserControl, IDisposable
{
    private readonly IProviderModelClient _models; private readonly VisionScene _scene = new(); private readonly HavenSceneControl _host; private CancellationTokenSource? _analysisCancellation; private string? _imagePath; private bool _disposed;
    public VisionPage(IProviderModelClient models)
    {
        _models = models; _host = new HavenSceneControl { Root = _scene.Root }; Content = _host; _host.InputSubmitted += input => { if (ReferenceEquals(input, _scene.Question)) _ = AnalyseAsync(_scene.Question.Text); };
        _scene.ImportRequested += async (_, _) => await PickImageAsync(); _scene.AnalyseRequested += prompt => _ = AnalyseAsync(prompt); _scene.OcrRequested += (_, _) => _ = AnalyseAsync("Read and transcribe all visible text in this image. Preserve line breaks and clearly mark uncertain characters."); _scene.StopRequested += (_, _) => _analysisCancellation?.Cancel(); _scene.OpenImagineRequested += (_, _) => { if (!string.IsNullOrWhiteSpace(_imagePath)) OpenInImagineRequested?.Invoke(_imagePath); else _scene.SetStatus("Import an image before opening it in Imagine."); }; SizeChanged += (_, e) => _scene.SetViewportWidth(e.NewSize.Width);
    }
    public event Action<string>? OpenInImagineRequested; public string? ImagePath => _imagePath;
    public Task LoadImageAsync(string path) { if (string.IsNullOrWhiteSpace(path) || !File.Exists(path)) { _scene.SetStatus("The requested image is unavailable."); return Task.CompletedTask; } _imagePath = Path.GetFullPath(path); _scene.SetImage(_imagePath); _scene.SetStatus("Image ready for visual analysis."); return Task.CompletedTask; }
    private async Task PickImageAsync() { var storage = TopLevel.GetTopLevel(this)?.StorageProvider; if (storage is null) { _scene.SetStatus("The platform file picker is unavailable."); return; } var files = await storage.OpenFilePickerAsync(new FilePickerOpenOptions { Title = "Open image in Vision", AllowMultiple = false }); var path = files.FirstOrDefault()?.TryGetLocalPath(); if (!string.IsNullOrWhiteSpace(path)) await LoadImageAsync(path); }
    private async Task AnalyseAsync(string prompt)
    {
        if (string.IsNullOrWhiteSpace(_imagePath) || !File.Exists(_imagePath)) { _scene.SetStatus("Import an image before asking Vision."); return; } if (string.IsNullOrWhiteSpace(prompt)) prompt = "Describe this image carefully, including important objects, visible text, layout and uncertainty."; _analysisCancellation?.Cancel(); _analysisCancellation?.Dispose(); var cancellation = new CancellationTokenSource(TimeSpan.FromSeconds(60)); _analysisCancellation = cancellation; _scene.SetBusy(true); _scene.SetStatus("Vision is analysing the image…");
        try { var available = await _models.GetModelsAsync(cancellation.Token); var model = available.FirstOrDefault(item => item.Supports(ToolCapability.Vision)); if (model is null) { _scene.SetStatus("No compatible vision model is available. The image was not sent to a text-only model."); return; } var response = await _models.CompleteAsync(new OllamaChatRequest(model.Name, [new OllamaMessage("user", prompt.Trim(), [_imagePath])], EffortLevel.Medium, "Act as Haven Vision. Analyse only the supplied image, distinguish observation from inference, transcribe visible text accurately, and state uncertainty."), cancellation.Token); _scene.SetResponse(response, model.Name); _scene.Question.Text = string.Empty; _scene.SetStatus("Analysis complete."); } catch (OperationCanceledException) when (cancellation.IsCancellationRequested) { _scene.SetStatus("Vision analysis stopped."); } catch (Exception exception) when (exception is HttpRequestException or IOException or InvalidOperationException) { _scene.SetStatus("Vision analysis failed: " + exception.Message); } finally { if (ReferenceEquals(_analysisCancellation, cancellation)) _analysisCancellation = null; cancellation.Dispose(); await Dispatcher.UIThread.InvokeAsync(() => _scene.SetBusy(false)); }
    }
    public void Dispose() { if (_disposed) return; _disposed = true; _analysisCancellation?.Cancel(); _analysisCancellation?.Dispose(); }
}

internal sealed class VisionScene
{
    public VisionScene()
    {
        Root = new HavenPage { Name = "Vision.Root", Layout = HavenLayout.Vertical }; Root.SetValue(HavenProperties.Width, HavenLength.Percent(100)); Root.SetValue(HavenProperties.Height, HavenLength.Percent(100)); Root.SetValue(HavenProperties.Gap, HavenLength.Px(10)); Root.SetValue(HavenProperties.Padding, HavenThickness.Parse("18px 20px")); Root.Accessibility.AccessibleName = "Vision visual understanding workspace";
        var header = new HavenContainer { Name = "Vision.Header", Layout = HavenLayout.Wrap }; header.SetValue(HavenProperties.Gap, HavenLength.Px(7)); Title = new HavenText { Content = "Vision", Level = TextLevel.H1 }; header.Add(Title); Import = Action("Vision.Import", "Open image", "plus"); header.Add(Import); Analyse = Action("Vision.Analyse", "Analyse", "vision"); header.Add(Analyse); Ocr = Action("Vision.Ocr", "Read text", "file"); header.Add(Ocr); Stop = Action("Vision.Stop", "Stop", "delete"); Stop.SetValue(HavenProperties.Visibility, HavenVisibility.Collapsed); header.Add(Stop); OpenImagine = Action("Vision.OpenImagine", "Edit in Imagine", "palette"); header.Add(OpenImagine); Root.Add(header);
        Body = new HavenContainer { Name = "Vision.Body", Layout = HavenLayout.Grid, Columns = "1.15fr .85fr", Rows = "1fr" }; Body.SetValue(HavenProperties.Width, HavenLength.Percent(100)); Body.SetValue(HavenProperties.MinHeight, HavenLength.Px(500)); Body.SetValue(HavenProperties.Gap, HavenLength.Px(14)); Root.Add(Body); Preview = new VisionPreviewElement { Name = "Vision.Preview" }; Preview.SetValue(HavenProperties.Column, 0); Preview.SetValue(HavenProperties.Width, HavenLength.Percent(100)); Preview.SetValue(HavenProperties.Height, HavenLength.Percent(100)); Body.Add(Preview); var panel = new HavenContainer { Name = "Vision.Panel", Layout = HavenLayout.Vertical }; panel.SetValue(HavenProperties.Column, 1); panel.SetValue(HavenProperties.Gap, HavenLength.Px(8)); panel.SetValue(HavenProperties.Overflow, HavenOverflow.Scroll); Body.Add(panel); Question = new Input { Name = "Vision.Question", Placeholder = "Ask about the image", Multiline = true, SubmitOnEnter = true }; Question.SetValue(HavenProperties.MinHeight, HavenLength.Px(90)); panel.Add(Question); Response = new HavenText { Name = "Vision.Response", Content = "Import an image, then ask a question or choose Read text." }; panel.Add(Response); Model = Muted("Vision.Model", string.Empty); panel.Add(Model); Status = Muted("Vision.Status", "No image loaded."); panel.Add(Status);
        Import.Invoked += (_, _) => ImportRequested?.Invoke(this, EventArgs.Empty); Analyse.Invoked += (_, _) => AnalyseRequested?.Invoke(Question.Text.Trim()); Ocr.Invoked += (_, _) => OcrRequested?.Invoke(this, EventArgs.Empty); Stop.Invoked += (_, _) => StopRequested?.Invoke(this, EventArgs.Empty); OpenImagine.Invoked += (_, _) => OpenImagineRequested?.Invoke(this, EventArgs.Empty); SetViewportWidth(1200);
    }
    public HavenPage Root { get; } public HavenContainer Body { get; } public HavenText Title { get; } public VisionPreviewElement Preview { get; } public Input Question { get; } public HavenText Response { get; } public HavenText Model { get; } public HavenText Status { get; } public HavenButton Import { get; } public HavenButton Analyse { get; } public HavenButton Ocr { get; } public HavenButton Stop { get; } public HavenButton OpenImagine { get; }
    public event EventHandler? ImportRequested; public event Action<string>? AnalyseRequested; public event EventHandler? OcrRequested; public event EventHandler? StopRequested; public event EventHandler? OpenImagineRequested; public void SetImage(string path) => Preview.Source = path; public void SetStatus(string value) => Status.Content = value; public void SetResponse(string value, string model) { Response.Content = value; Model.Content = "Model: " + model; } public void SetBusy(bool busy) { Analyse.SetValue(HavenProperties.Enabled, !busy); Ocr.SetValue(HavenProperties.Enabled, !busy); Stop.SetValue(HavenProperties.Visibility, busy ? HavenVisibility.Visible : HavenVisibility.Collapsed); } public void SetViewportWidth(double width) { Body.Columns = width < 760 ? "1fr" : "1.15fr .85fr"; Body.Rows = width < 760 ? "Auto Auto" : "1fr"; Preview.SetValue(HavenProperties.Column, 0); Body.Children[1].SetValue(HavenProperties.Column, width < 760 ? 0 : 1); Body.Children[1].SetValue(HavenProperties.Row, width < 760 ? 1 : 0); } private static HavenButton Action(string name, string content, string icon) => new() { Name = name, Content = content, IconKey = icon, Variant = ButtonVariant.Ghost }; private static HavenText Muted(string name, string content) { var value = new HavenText { Name = name, Content = content }; value.SetValue(HavenProperties.Foreground, "TextSecondary"); value.SetValue(HavenProperties.FontSize, 11d); return value; }
}

internal sealed class VisionPreviewElement : HavenElement, IHavenDrawCommandSource
{
    private string? _source; public string? Source { get => _source; set { if (_source == value) return; _source = value; Invalidate(); } } public VisionPreviewElement() { Accessibility.Role = HavenAccessibleRole.Image; Accessibility.AccessibleName = "Vision image preview"; SetValue(HavenProperties.Background, "SurfaceRaised"); SetValue(HavenProperties.BorderColor, "Border"); SetValue(HavenProperties.BorderWidth, HavenLength.Px(1)); SetValue(HavenProperties.Radius, HavenCornerRadius.Uniform(HavenLength.Px(16))); } public void Draw(HavenDrawingContext context, double opacity) { context.Add(new HavenFillRoundedRectCommand(Bounds, new HavenTokenBrush("SurfaceRaised"), 16, opacity)); if (!string.IsNullOrWhiteSpace(_source)) context.Add(new HavenImageCommand(new HavenRect(Bounds.X + 12, Bounds.Y + 12, Math.Max(1, Bounds.Width - 24), Math.Max(1, Bounds.Height - 24)), new HavenImage(_source), HavenImageLayout.Contain, opacity)); else context.Add(new HavenTextCommand(new HavenRect(Bounds.X + 24, Bounds.Y + 24, Math.Max(1, Bounds.Width - 48), 60), new HavenTextLayout("Open an image to inspect it", "Segoe UI", 18, 600, Math.Max(1, Bounds.Width - 48)), new HavenTokenBrush("TextSecondary"), opacity)); }
}
