using System.Globalization;
using System.IO.Compression;
using System.Xml.Linq;
using Haven.Application;
using Haven.Core;

namespace Haven.Infrastructure;

public sealed class DataXlsxFormatService : IDataWorkbookFormatService
{
    private static readonly XNamespace Main = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
    private static readonly XNamespace Rel = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
    private static readonly XNamespace PackageRel = "http://schemas.openxmlformats.org/package/2006/relationships";
    public IReadOnlyList<string> ImportExtensions { get; } = [".xlsx"]; public IReadOnlyList<string> ExportExtensions { get; } = [".xlsx"];

    public async Task<DataWorkbook> ImportAsync(string sourcePath, CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourcePath); cancellationToken.ThrowIfCancellationRequested(); EnsureExtension(sourcePath, ImportExtensions);
        await using var stream = new FileStream(sourcePath, FileMode.Open, FileAccess.Read, FileShare.Read, 64 * 1024, FileOptions.Asynchronous | FileOptions.SequentialScan); using var archive = new ZipArchive(stream, ZipArchiveMode.Read, leaveOpen: false);
        var workbookXml = Load(Required(archive, "xl/workbook.xml")); var relsXml = Load(Required(archive, "xl/_rels/workbook.xml.rels"));
        var relationships = relsXml.Root?.Elements(PackageRel + "Relationship").ToDictionary(x => (string?)x.Attribute("Id") ?? string.Empty, x => (string?)x.Attribute("Target") ?? string.Empty, StringComparer.Ordinal) ?? []; var sharedStrings = ReadSharedStrings(archive);
        var workbook = DataWorkbook.Create(Path.GetFileNameWithoutExtension(sourcePath)); workbook.Sheets.Clear(); workbook.Queries.Clear(); var order = 0;
        foreach (var sheetElement in workbookXml.Descendants(Main + "sheet")) { cancellationToken.ThrowIfCancellationRequested(); var name = (string?)sheetElement.Attribute("name") ?? $"Sheet {order + 1}"; var relationshipId = (string?)sheetElement.Attribute(Rel + "id"); if (string.IsNullOrWhiteSpace(relationshipId) || !relationships.TryGetValue(relationshipId, out var target)) continue; var entry = archive.GetEntry(NormalizeWorksheetTarget(target)); if (entry is null) continue; var sheet = DataSheet.Create(order++, name); ReadSheet(Load(entry), sheet, sharedStrings); workbook.Sheets.Add(sheet); }
        if (workbook.Sheets.Count == 0) workbook.Sheets.Add(DataSheet.Create(0, "Sheet 1")); workbook.Queries.Add(DataQuery.Create("Query 1")); workbook.Metadata["sourceFormat"] = "xlsx"; workbook.Metadata["compatibilityNote"] = "Imported sheet names, cell values and formulas. Formatting, charts, drawings, macros and external links are not imported by this Data slice."; workbook.Normalize(); return workbook;
    }

    public async Task<string> ExportAsync(DataWorkbook workbook, string destinationPath, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(workbook); ArgumentException.ThrowIfNullOrWhiteSpace(destinationPath); cancellationToken.ThrowIfCancellationRequested(); EnsureExtension(destinationPath, ExportExtensions); workbook.Normalize(); var fullPath = Path.GetFullPath(destinationPath); var directory = Path.GetDirectoryName(fullPath) ?? throw new InvalidOperationException("The export destination has no directory."); Directory.CreateDirectory(directory); var temporary = Path.Combine(directory, $".{Path.GetFileName(fullPath)}.{Guid.NewGuid():N}.tmp");
        try { await using (var file = new FileStream(temporary, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None, 64 * 1024, FileOptions.Asynchronous | FileOptions.WriteThrough)) using (var archive = new ZipArchive(file, ZipArchiveMode.Create, leaveOpen: true)) { WriteXml(archive, "[Content_Types].xml", BuildContentTypes(workbook.Sheets.Count)); WriteXml(archive, "_rels/.rels", BuildRootRelationships()); WriteXml(archive, "xl/workbook.xml", BuildWorkbook(workbook)); WriteXml(archive, "xl/_rels/workbook.xml.rels", BuildWorkbookRelationships(workbook.Sheets.Count)); for (var i = 0; i < workbook.Sheets.Count; i++) { cancellationToken.ThrowIfCancellationRequested(); WriteXml(archive, $"xl/worksheets/sheet{i + 1}.xml", BuildSheet(workbook.Sheets[i])); } } ValidatePackage(temporary, workbook.Sheets.Count); File.Move(temporary, fullPath, overwrite: true); return fullPath; } finally { TryDelete(temporary); }
    }

    private static void ReadSheet(XDocument xml, DataSheet sheet, IReadOnlyList<string> sharedStrings)
    {
        foreach (var cellElement in xml.Descendants(Main + "c")) { var reference = (string?)cellElement.Attribute("r"); if (!TryParseCellReference(reference, out var row, out var column)) continue; var type = (string?)cellElement.Attribute("t") ?? string.Empty; var formulaText = cellElement.Element(Main + "f")?.Value ?? string.Empty; var formula = string.IsNullOrWhiteSpace(formulaText) ? string.Empty : "=" + formulaText; string value; DataCellKind kind; if (type == "inlineStr") { value = string.Concat(cellElement.Descendants(Main + "t").Select(x => x.Value)); kind = DataCellKind.Text; } else { var raw = cellElement.Element(Main + "v")?.Value ?? string.Empty; if (type == "s" && int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var index) && index >= 0 && index < sharedStrings.Count) { value = sharedStrings[index]; kind = DataCellKind.Text; } else if (type == "b") { value = raw == "1" ? "true" : "false"; kind = DataCellKind.Boolean; } else { value = raw; kind = DataCell.InferKind(value); } } sheet.SetCell(row, column, value, formula, string.IsNullOrWhiteSpace(formula) ? kind : DataCellKind.Formula); }
    }

    private static IReadOnlyList<string> ReadSharedStrings(ZipArchive archive) { var entry = archive.GetEntry("xl/sharedStrings.xml"); if (entry is null) return []; var xml = Load(entry); return xml.Root?.Elements(Main + "si").Select(item => string.Concat(item.Descendants(Main + "t").Select(text => text.Value))).ToArray() ?? []; }
    private static XDocument BuildSheet(DataSheet sheet) { var rows = sheet.Cells.OrderBy(cell => cell.Row).ThenBy(cell => cell.Column).GroupBy(cell => cell.Row).Select(group => new XElement(Main + "row", new XAttribute("r", group.Key + 1), group.Select(BuildCell))); return new XDocument(new XDeclaration("1.0", "UTF-8", "yes"), new XElement(Main + "worksheet", new XElement(Main + "sheetData", rows))); }
    private static XElement BuildCell(DataCell cell)
    {
        var reference = CellReference(cell.Row, cell.Column); if (!string.IsNullOrWhiteSpace(cell.Formula)) { var formula = cell.Formula.StartsWith('=') ? cell.Formula[1..] : cell.Formula; var element = new XElement(Main + "c", new XAttribute("r", reference), new XElement(Main + "f", formula)); if (!string.IsNullOrWhiteSpace(cell.Value)) element.Add(new XElement(Main + "v", cell.Value)); return element; } if (cell.Kind == DataCellKind.Boolean && bool.TryParse(cell.Value, out var boolean)) return new XElement(Main + "c", new XAttribute("r", reference), new XAttribute("t", "b"), new XElement(Main + "v", boolean ? "1" : "0")); if (cell.Kind == DataCellKind.Number && double.TryParse(cell.Value, NumberStyles.Float, CultureInfo.InvariantCulture, out var number)) return new XElement(Main + "c", new XAttribute("r", reference), new XElement(Main + "v", number.ToString("R", CultureInfo.InvariantCulture))); return new XElement(Main + "c", new XAttribute("r", reference), new XAttribute("t", "inlineStr"), new XElement(Main + "is", new XElement(Main + "t", new XAttribute(XNamespace.Xml + "space", "preserve"), cell.Value ?? string.Empty)));
    }

    private static XDocument BuildWorkbook(DataWorkbook workbook) { var sheets = workbook.Sheets.Select((sheet, index) => new XElement(Main + "sheet", new XAttribute("name", SafeSheetName(sheet.Name, index)), new XAttribute("sheetId", index + 1), new XAttribute(Rel + "id", $"rId{index + 1}"))); return new XDocument(new XDeclaration("1.0", "UTF-8", "yes"), new XElement(Main + "workbook", new XAttribute(XNamespace.Xmlns + "r", Rel), new XElement(Main + "sheets", sheets), new XElement(Main + "calcPr", new XAttribute("fullCalcOnLoad", "1"), new XAttribute("forceFullCalc", "1")))); }
    private static XDocument BuildWorkbookRelationships(int count) => new(new XDeclaration("1.0", "UTF-8", "yes"), new XElement(PackageRel + "Relationships", Enumerable.Range(1, count).Select(i => new XElement(PackageRel + "Relationship", new XAttribute("Id", $"rId{i}"), new XAttribute("Type", "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"), new XAttribute("Target", $"worksheets/sheet{i}.xml")))));
    private static XDocument BuildRootRelationships() => new(new XDeclaration("1.0", "UTF-8", "yes"), new XElement(PackageRel + "Relationships", new XElement(PackageRel + "Relationship", new XAttribute("Id", "rId1"), new XAttribute("Type", "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"), new XAttribute("Target", "xl/workbook.xml"))));
    private static XDocument BuildContentTypes(int count) { XNamespace types = "http://schemas.openxmlformats.org/package/2006/content-types"; return new XDocument(new XDeclaration("1.0", "UTF-8", "yes"), new XElement(types + "Types", new XElement(types + "Default", new XAttribute("Extension", "rels"), new XAttribute("ContentType", "application/vnd.openxmlformats-package.relationships+xml")), new XElement(types + "Default", new XAttribute("Extension", "xml"), new XAttribute("ContentType", "application/xml")), new XElement(types + "Override", new XAttribute("PartName", "/xl/workbook.xml"), new XAttribute("ContentType", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml")), Enumerable.Range(1, count).Select(i => new XElement(types + "Override", new XAttribute("PartName", $"/xl/worksheets/sheet{i}.xml"), new XAttribute("ContentType", "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"))))); }
    private static void WriteXml(ZipArchive archive, string path, XDocument xml) { var entry = archive.CreateEntry(path, CompressionLevel.Optimal); using var stream = entry.Open(); xml.Save(stream); }
    private static XDocument Load(ZipArchiveEntry entry) { using var stream = entry.Open(); return XDocument.Load(stream, LoadOptions.PreserveWhitespace); }
    private static ZipArchiveEntry Required(ZipArchive archive, string path) => archive.GetEntry(path) ?? throw new InvalidDataException($"The workbook is missing required part '{path}'.");
    private static string NormalizeWorksheetTarget(string target) { var value = target.Replace('\\', '/').TrimStart('/'); while (value.StartsWith("../", StringComparison.Ordinal)) value = value[3..]; return value.StartsWith("xl/", StringComparison.OrdinalIgnoreCase) ? value : "xl/" + value; }
    private static void EnsureExtension(string path, IReadOnlyList<string> supported) { var extension = Path.GetExtension(path); if (!supported.Contains(extension, StringComparer.OrdinalIgnoreCase)) throw new NotSupportedException($"Unsupported workbook format '{extension}'. Supported: {string.Join(", ", supported)}."); }
    private static string SafeSheetName(string name, int index) { var value = string.IsNullOrWhiteSpace(name) ? $"Sheet {index + 1}" : name.Trim(); foreach (var c in new[] { '[', ']', ':', '*', '?', '/', '\\' }) value = value.Replace(c, '_'); if (value.Length > 31) value = value[..31]; return value.Length == 0 ? $"Sheet {index + 1}" : value; }
    private static string CellReference(int row, int column) { var n = column + 1; var letters = string.Empty; while (n > 0) { n--; letters = (char)('A' + n % 26) + letters; n /= 26; } return letters + (row + 1).ToString(CultureInfo.InvariantCulture); }
    public static bool TryParseCellReference(string? reference, out int row, out int column) { row = column = 0; if (string.IsNullOrWhiteSpace(reference)) return false; var i = 0; var col = 0; while (i < reference.Length && char.IsLetter(reference[i])) { col = col * 26 + (char.ToUpperInvariant(reference[i]) - 'A' + 1); i++; } if (i == 0 || !int.TryParse(reference[i..], NumberStyles.Integer, CultureInfo.InvariantCulture, out var parsedRow) || parsedRow < 1 || col < 1) return false; row = parsedRow - 1; column = col - 1; return true; }
    private static void ValidatePackage(string path, int sheetCount) { using var archive = ZipFile.OpenRead(path); _ = Required(archive, "[Content_Types].xml"); _ = Required(archive, "xl/workbook.xml"); _ = Required(archive, "xl/_rels/workbook.xml.rels"); for (var i = 1; i <= sheetCount; i++) _ = Required(archive, $"xl/worksheets/sheet{i}.xml"); }
    private static void TryDelete(string path) { try { if (File.Exists(path)) File.Delete(path); } catch (IOException) { } catch (UnauthorizedAccessException) { } }
}
