aotassemblies=false
androidaddkeepalives=
androidaotmode=interpreter
androidembedprofilers=
androidenableprofiledaot=false
androiddextool=d8
androidlinktool=
androidlinkresources=
androidpackageformat=apk
embedassembliesintoapk=true
androidlinkmode=none
androidlinkskip=
androidsdkbuildtoolsversion=36.0.0
androidsdkpath=c:\program files (x86)\android\android-sdk\
androidndkpath=
javasdkpath=c:\program files\android\openjdk\jdk-21.0.8\
androidsequencepointsmode=none
androidnetsdkversion=36.1.43
androiduselatestplatformsdk=false
targetframeworkversion=v10.0
androidcreatepackageperabi=
androidgeneratejnimarshalmethods=false
os=windows_nt
androidincludedebugsymbols=true
androidpackagenamingpolicy=lowercasecrc64
_nugetassetsfilehash=1a100723903eaf29646301c9589e37556b37ca3b74872670371b1f99f030cc24
typemapkind=strings-asm
androidmanifestplaceholders=
projectfullpath=c:\users\jacob\onedrive\personal files\development\visual studio\haven ai\source\src\haven.android\haven.android.csproj
androidusedesignerassembly=true
